const std = @import("std");
const builtin = @import("builtin");

const testTokenize = @import("../tokenizer.zig").testTokenize;

const Token = @This();

tag: Tag,
loc: Loc,
eob: bool,

pub const Index = u32;

pub const Loc = struct {
    start: usize,
    end: usize,
};

pub const keywords = std.StaticStringMap(Tag).initComptime(.{
    .{ "abs", .keyword_abs },
    .{ "acos", .keyword_acos },
    .{ "asin", .keyword_asin },
    .{ "atan", .keyword_atan },
    .{ "avg", .keyword_avg },
    .{ "bin", .keyword_bin },
    .{ "binr", .keyword_binr },
    .{ "cor", .keyword_cor },
    .{ "cos", .keyword_cos },
    .{ "cov", .keyword_cov },
    .{ "delete", .keyword_delete },
    .{ "dev", .keyword_dev },
    .{ "div", .keyword_div },
    .{ "do", .keyword_do },
    .{ "enlist", .keyword_enlist },
    .{ "exec", .keyword_exec },
    .{ "exit", .keyword_exit },
    .{ "exp", .keyword_exp },
    .{ "getenv", .keyword_getenv },
    .{ "hopen", .keyword_hopen },
    .{ "if", .keyword_if },
    .{ "in", .keyword_in },
    .{ "insert", .keyword_insert },
    .{ "last", .keyword_last },
    .{ "like", .keyword_like },
    .{ "log", .keyword_log },
    .{ "max", .keyword_max },
    .{ "min", .keyword_min },
    .{ "prd", .keyword_prd },
    .{ "select", .keyword_select },
    .{ "setenv", .keyword_setenv },
    .{ "sin", .keyword_sin },
    .{ "sqrt", .keyword_sqrt },
    .{ "ss", .keyword_ss },
    .{ "sum", .keyword_sum },
    .{ "tan", .keyword_tan },
    .{ "update", .keyword_update },
    .{ "var", .keyword_var },
    .{ "wavg", .keyword_wavg },
    .{ "while", .keyword_while },
    .{ "within", .keyword_within },
    .{ "wsum", .keyword_wsum },
    .{ "xexp", .keyword_xexp },

    .{ "aj", .keyword_q_aj },
    .{ "aj0", .keyword_q_aj0 },
    .{ "ajf", .keyword_q_ajf },
    .{ "ajf0", .keyword_q_ajf0 },
    .{ "all", .keyword_q_all },
    .{ "and", .keyword_q_and },
    .{ "any", .keyword_q_any },
    .{ "asc", .keyword_q_asc },
    .{ "asof", .keyword_q_asof },
    .{ "attr", .keyword_q_attr },
    .{ "avgs", .keyword_q_avgs },
    .{ "ceiling", .keyword_q_ceiling },
    .{ "cols", .keyword_q_cols },
    .{ "count", .keyword_q_count },
    .{ "cross", .keyword_q_cross },
    .{ "csv", .keyword_q_csv },
    .{ "cut", .keyword_q_cut },
    .{ "deltas", .keyword_q_deltas },
    .{ "desc", .keyword_q_desc },
    .{ "differ", .keyword_q_differ },
    .{ "distinct", .keyword_q_distinct },
    .{ "dsave", .keyword_q_dsave },
    .{ "each", .keyword_q_each },
    .{ "ej", .keyword_q_ej },
    .{ "ema", .keyword_q_ema },
    .{ "eval", .keyword_q_eval },
    .{ "except", .keyword_q_except },
    .{ "fby", .keyword_q_fby },
    .{ "fills", .keyword_q_fills },
    .{ "first", .keyword_q_first },
    .{ "fkeys", .keyword_q_fkeys },
    .{ "flip", .keyword_q_flip },
    .{ "floor", .keyword_q_floor },
    .{ "get", .keyword_q_get },
    .{ "group", .keyword_q_group },
    .{ "gtime", .keyword_q_gtime },
    .{ "hclose", .keyword_q_hclose },
    .{ "hcount", .keyword_q_hcount },
    .{ "hdel", .keyword_q_hdel },
    .{ "hsym", .keyword_q_hsym },
    .{ "iasc", .keyword_q_iasc },
    .{ "idesc", .keyword_q_idesc },
    .{ "ij", .keyword_q_ij },
    .{ "ijf", .keyword_q_ijf },
    .{ "inter", .keyword_q_inter },
    .{ "inv", .keyword_q_inv },
    .{ "key", .keyword_q_key },
    .{ "keys", .keyword_q_keys },
    .{ "lj", .keyword_q_lj },
    .{ "ljf", .keyword_q_ljf },
    .{ "load", .keyword_q_load },
    .{ "lower", .keyword_q_lower },
    .{ "lsq", .keyword_q_lsq },
    .{ "ltime", .keyword_q_ltime },
    .{ "ltrim", .keyword_q_ltrim },
    .{ "mavg", .keyword_q_mavg },
    .{ "maxs", .keyword_q_maxs },
    .{ "mcount", .keyword_q_mcount },
    .{ "md5", .keyword_q_md5 },
    .{ "mdev", .keyword_q_mdev },
    .{ "med", .keyword_q_med },
    .{ "meta", .keyword_q_meta },
    .{ "mins", .keyword_q_mins },
    .{ "mmax", .keyword_q_mmax },
    .{ "mmin", .keyword_q_mmin },
    .{ "mmu", .keyword_q_mmu },
    .{ "mod", .keyword_q_mod },
    .{ "msum", .keyword_q_msum },
    .{ "neg", .keyword_q_neg },
    .{ "next", .keyword_q_next },
    .{ "not", .keyword_q_not },
    .{ "null", .keyword_q_null },
    .{ "or", .keyword_q_or },
    .{ "over", .keyword_q_over },
    .{ "parse", .keyword_q_parse },
    .{ "peach", .keyword_q_peach },
    .{ "pj", .keyword_q_pj },
    .{ "prds", .keyword_q_prds },
    .{ "prev", .keyword_q_prev },
    .{ "prior", .keyword_q_prior },
    .{ "rand", .keyword_q_rand },
    .{ "rank", .keyword_q_rank },
    .{ "ratios", .keyword_q_ratios },
    .{ "raze", .keyword_q_raze },
    .{ "read0", .keyword_q_read0 },
    .{ "read1", .keyword_q_read1 },
    .{ "reciprocal", .keyword_q_reciprocal },
    .{ "reval", .keyword_q_reval },
    .{ "reverse", .keyword_q_reverse },
    .{ "rload", .keyword_q_rload },
    .{ "rotate", .keyword_q_rotate },
    .{ "rsave", .keyword_q_rsave },
    .{ "rtrim", .keyword_q_rtrim },
    .{ "save", .keyword_q_save },
    .{ "scan", .keyword_q_scan },
    .{ "scov", .keyword_q_scov },
    .{ "sdev", .keyword_q_sdev },
    .{ "set", .keyword_q_set },
    .{ "show", .keyword_q_show },
    .{ "signum", .keyword_q_signum },
    .{ "ssr", .keyword_q_ssr },
    .{ "string", .keyword_q_string },
    .{ "sublist", .keyword_q_sublist },
    .{ "sums", .keyword_q_sums },
    .{ "sv", .keyword_q_sv },
    .{ "svar", .keyword_q_svar },
    .{ "system", .keyword_q_system },
    .{ "tables", .keyword_q_tables },
    .{ "til", .keyword_q_til },
    .{ "trim", .keyword_q_trim },
    .{ "type", .keyword_q_type },
    .{ "uj", .keyword_q_uj },
    .{ "ujf", .keyword_q_ujf },
    .{ "ungroup", .keyword_q_ungroup },
    .{ "union", .keyword_q_union },
    .{ "upper", .keyword_q_upper },
    .{ "upsert", .keyword_q_upsert },
    .{ "value", .keyword_q_value },
    .{ "view", .keyword_q_view },
    .{ "views", .keyword_q_views },
    .{ "vs", .keyword_q_vs },
    .{ "where", .keyword_q_where },
    .{ "wj", .keyword_q_wj },
    .{ "wj1", .keyword_q_wj1 },
    .{ "ww", .keyword_q_ww },
    .{ "xasc", .keyword_q_xasc },
    .{ "xbar", .keyword_q_xbar },
    .{ "xcol", .keyword_q_xcol },
    .{ "xcols", .keyword_q_xcols },
    .{ "xdesc", .keyword_q_xdesc },
    .{ "xgroup", .keyword_q_xgroup },
    .{ "xkey", .keyword_q_xkey },
    .{ "xlog", .keyword_q_xlog },
    .{ "xprev", .keyword_q_xprev },
    .{ "xrank", .keyword_q_xrank },
});

pub fn getKeyword(bytes: []const u8) ?Tag {
    return keywords.get(bytes);
}

pub const Tag = enum {
    // Punctuation
    l_paren,
    r_paren,
    l_brace,
    r_brace,
    l_bracket,
    r_bracket,
    semicolon,

    // Verbs
    colon,
    colon_colon,
    plus,
    plus_colon,
    minus,
    minus_colon,
    asterisk,
    asterisk_colon,
    percent,
    percent_colon,
    bang,
    bang_colon,
    ampersand,
    ampersand_colon,
    pipe,
    pipe_colon,
    angle_bracket_left,
    angle_bracket_left_colon,
    angle_bracket_left_equal,
    angle_bracket_left_right,
    angle_bracket_right,
    angle_bracket_right_colon,
    angle_bracket_right_equal,
    equal,
    equal_colon,
    tilde,
    tilde_colon,
    comma,
    comma_colon,
    caret,
    caret_colon,
    hash,
    hash_colon,
    underscore,
    underscore_colon,
    dollar,
    dollar_colon,
    question_mark,
    question_mark_colon,
    at,
    at_colon,
    dot,
    dot_colon,
    zero_colon,
    zero_colon_colon,
    one_colon,
    one_colon_colon,
    two_colon,

    // Adverbs
    apostrophe,
    apostrophe_colon,
    slash,
    slash_colon,
    backslash,
    backslash_colon,

    // Literals
    number_literal,
    string_literal,
    symbol_literal,
    symbol_list_literal,
    identifier,

    // Misc.
    comment,
    invalid,
    os,
    os_param,
    eof,

    // Keywords : -1","sv"keyword_",/:string asc .Q.res;
    keyword_abs,
    keyword_acos,
    keyword_asin,
    keyword_atan,
    keyword_avg,
    keyword_bin,
    keyword_binr,
    keyword_cor,
    keyword_cos,
    keyword_cov,
    keyword_delete,
    keyword_dev,
    keyword_div,
    keyword_do,
    keyword_enlist,
    keyword_exec,
    keyword_exit,
    keyword_exp,
    keyword_getenv,
    keyword_hopen,
    keyword_if,
    keyword_in,
    keyword_insert,
    keyword_last,
    keyword_like,
    keyword_log,
    keyword_max,
    keyword_min,
    keyword_prd,
    keyword_select,
    keyword_setenv,
    keyword_sin,
    keyword_sqrt,
    keyword_ss,
    keyword_sum,
    keyword_tan,
    keyword_update,
    keyword_var,
    keyword_wavg,
    keyword_while,
    keyword_within,
    keyword_wsum,
    keyword_xexp,

    // Q Keywords : -1","sv"keyword_q_",/:string asc 1_key`.q;
    keyword_q_aj,
    keyword_q_aj0,
    keyword_q_ajf,
    keyword_q_ajf0,
    keyword_q_all,
    keyword_q_and,
    keyword_q_any,
    keyword_q_asc,
    keyword_q_asof,
    keyword_q_attr,
    keyword_q_avgs,
    keyword_q_ceiling,
    keyword_q_cols,
    keyword_q_count,
    keyword_q_cross,
    keyword_q_csv,
    keyword_q_cut,
    keyword_q_deltas,
    keyword_q_desc,
    keyword_q_differ,
    keyword_q_distinct,
    keyword_q_dsave,
    keyword_q_each,
    keyword_q_ej,
    keyword_q_ema,
    keyword_q_eval,
    keyword_q_except,
    keyword_q_fby,
    keyword_q_fills,
    keyword_q_first,
    keyword_q_fkeys,
    keyword_q_flip,
    keyword_q_floor,
    keyword_q_get,
    keyword_q_group,
    keyword_q_gtime,
    keyword_q_hclose,
    keyword_q_hcount,
    keyword_q_hdel,
    keyword_q_hsym,
    keyword_q_iasc,
    keyword_q_idesc,
    keyword_q_ij,
    keyword_q_ijf,
    keyword_q_inter,
    keyword_q_inv,
    keyword_q_key,
    keyword_q_keys,
    keyword_q_lj,
    keyword_q_ljf,
    keyword_q_load,
    keyword_q_lower,
    keyword_q_lsq,
    keyword_q_ltime,
    keyword_q_ltrim,
    keyword_q_mavg,
    keyword_q_maxs,
    keyword_q_mcount,
    keyword_q_md5,
    keyword_q_mdev,
    keyword_q_med,
    keyword_q_meta,
    keyword_q_mins,
    keyword_q_mmax,
    keyword_q_mmin,
    keyword_q_mmu,
    keyword_q_mod,
    keyword_q_msum,
    keyword_q_neg,
    keyword_q_next,
    keyword_q_not,
    keyword_q_null,
    keyword_q_or,
    keyword_q_over,
    keyword_q_parse,
    keyword_q_peach,
    keyword_q_pj,
    keyword_q_prds,
    keyword_q_prev,
    keyword_q_prior,
    keyword_q_rand,
    keyword_q_rank,
    keyword_q_ratios,
    keyword_q_raze,
    keyword_q_read0,
    keyword_q_read1,
    keyword_q_reciprocal,
    keyword_q_reval,
    keyword_q_reverse,
    keyword_q_rload,
    keyword_q_rotate,
    keyword_q_rsave,
    keyword_q_rtrim,
    keyword_q_save,
    keyword_q_scan,
    keyword_q_scov,
    keyword_q_sdev,
    keyword_q_set,
    keyword_q_show,
    keyword_q_signum,
    keyword_q_ssr,
    keyword_q_string,
    keyword_q_sublist,
    keyword_q_sums,
    keyword_q_sv,
    keyword_q_svar,
    keyword_q_system,
    keyword_q_tables,
    keyword_q_til,
    keyword_q_trim,
    keyword_q_type,
    keyword_q_uj,
    keyword_q_ujf,
    keyword_q_ungroup,
    keyword_q_union,
    keyword_q_upper,
    keyword_q_upsert,
    keyword_q_value,
    keyword_q_view,
    keyword_q_views,
    keyword_q_vs,
    keyword_q_where,
    keyword_q_wj,
    keyword_q_wj1,
    keyword_q_ww,
    keyword_q_xasc,
    keyword_q_xbar,
    keyword_q_xcol,
    keyword_q_xcols,
    keyword_q_xdesc,
    keyword_q_xgroup,
    keyword_q_xkey,
    keyword_q_xlog,
    keyword_q_xprev,
    keyword_q_xrank,

    pub fn lexeme(tag: Tag) ?[]const u8 {
        return switch (tag) {
            .number_literal,
            .string_literal,
            .symbol_literal,
            .symbol_list_literal,
            .identifier,
            .comment,
            .invalid,
            .eof,
            .os,
            .os_param,
            => null,

            .l_paren => "(",
            .r_paren => ")",
            .l_brace => "{",
            .r_brace => "}",
            .l_bracket => "[",
            .r_bracket => "]",
            .semicolon => ";",
            .colon => ":",
            .colon_colon => "::",
            .plus => "+",
            .plus_colon => "+:",
            .minus => "-",
            .minus_colon => "-:",
            .asterisk => "*",
            .asterisk_colon => "*:",
            .percent => "%",
            .percent_colon => "%:",
            .bang => "!",
            .bang_colon => "!:",
            .ampersand => "&",
            .ampersand_colon => "&:",
            .pipe => "|",
            .pipe_colon => "|:",
            .angle_bracket_left => "<",
            .angle_bracket_left_colon => "<:",
            .angle_bracket_left_equal => "<=",
            .angle_bracket_left_right => "<>",
            .angle_bracket_right => ">",
            .angle_bracket_right_colon => ">:",
            .angle_bracket_right_equal => ">=",
            .equal => "=",
            .equal_colon => "=:",
            .tilde => "~",
            .tilde_colon => "~:",
            .comma => ",",
            .comma_colon => ",:",
            .caret => "^",
            .caret_colon => "^:",
            .hash => "#",
            .hash_colon => "#:",
            .underscore => "_",
            .underscore_colon => "_:",
            .dollar => "$",
            .dollar_colon => "$:",
            .question_mark => "?",
            .question_mark_colon => "?:",
            .at => "@",
            .at_colon => "@:",
            .dot => ".",
            .dot_colon => ".:",
            .zero_colon => "0:",
            .zero_colon_colon => "0::",
            .one_colon => "1:",
            .one_colon_colon => "1::",
            .two_colon => "2:",
            .apostrophe => "'",
            .apostrophe_colon => "':",
            .slash => "/",
            .slash_colon => "/:",
            .backslash => "\\",
            .backslash_colon => "\\:",

            .keyword_abs => "abs",
            .keyword_acos => "acos",
            .keyword_asin => "asin",
            .keyword_atan => "atan",
            .keyword_avg => "avg",
            .keyword_bin => "bin",
            .keyword_binr => "binr",
            .keyword_cor => "cor",
            .keyword_cos => "cos",
            .keyword_cov => "cov",
            .keyword_delete => "delete",
            .keyword_dev => "dev",
            .keyword_div => "div",
            .keyword_do => "do",
            .keyword_enlist => "enlist",
            .keyword_exec => "exec",
            .keyword_exit => "exit",
            .keyword_exp => "exp",
            .keyword_getenv => "getenv",
            .keyword_hopen => "hopen",
            .keyword_if => "if",
            .keyword_in => "in",
            .keyword_insert => "insert",
            .keyword_last => "last",
            .keyword_like => "like",
            .keyword_log => "log",
            .keyword_max => "max",
            .keyword_min => "min",
            .keyword_prd => "prd",
            .keyword_select => "select",
            .keyword_setenv => "setenv",
            .keyword_sin => "sin",
            .keyword_sqrt => "sqrt",
            .keyword_ss => "ss",
            .keyword_sum => "sum",
            .keyword_tan => "tan",
            .keyword_update => "update",
            .keyword_var => "var",
            .keyword_wavg => "wavg",
            .keyword_while => "while",
            .keyword_within => "within",
            .keyword_wsum => "wsum",
            .keyword_xexp => "xexp",

            .keyword_q_aj => "aj",
            .keyword_q_aj0 => "aj0",
            .keyword_q_ajf => "ajf",
            .keyword_q_ajf0 => "ajf0",
            .keyword_q_all => "all",
            .keyword_q_and => "and",
            .keyword_q_any => "any",
            .keyword_q_asc => "asc",
            .keyword_q_asof => "asof",
            .keyword_q_attr => "attr",
            .keyword_q_avgs => "avgs",
            .keyword_q_ceiling => "ceiling",
            .keyword_q_cols => "cols",
            .keyword_q_count => "count",
            .keyword_q_cross => "cross",
            .keyword_q_csv => "csv",
            .keyword_q_cut => "cut",
            .keyword_q_deltas => "deltas",
            .keyword_q_desc => "desc",
            .keyword_q_differ => "differ",
            .keyword_q_distinct => "distinct",
            .keyword_q_dsave => "dsave",
            .keyword_q_each => "each",
            .keyword_q_ej => "ej",
            .keyword_q_ema => "ema",
            .keyword_q_eval => "eval",
            .keyword_q_except => "except",
            .keyword_q_fby => "fby",
            .keyword_q_fills => "fills",
            .keyword_q_first => "first",
            .keyword_q_fkeys => "fkeys",
            .keyword_q_flip => "flip",
            .keyword_q_floor => "floor",
            .keyword_q_get => "get",
            .keyword_q_group => "group",
            .keyword_q_gtime => "gtime",
            .keyword_q_hclose => "hclose",
            .keyword_q_hcount => "hcount",
            .keyword_q_hdel => "hdel",
            .keyword_q_hsym => "hsym",
            .keyword_q_iasc => "iasc",
            .keyword_q_idesc => "idesc",
            .keyword_q_ij => "ij",
            .keyword_q_ijf => "ijf",
            .keyword_q_inter => "inter",
            .keyword_q_inv => "inv",
            .keyword_q_key => "key",
            .keyword_q_keys => "keys",
            .keyword_q_lj => "lj",
            .keyword_q_ljf => "ljf",
            .keyword_q_load => "load",
            .keyword_q_lower => "lower",
            .keyword_q_lsq => "lsq",
            .keyword_q_ltime => "ltime",
            .keyword_q_ltrim => "ltrim",
            .keyword_q_mavg => "mavg",
            .keyword_q_maxs => "maxs",
            .keyword_q_mcount => "mcount",
            .keyword_q_md5 => "md5",
            .keyword_q_mdev => "mdev",
            .keyword_q_med => "med",
            .keyword_q_meta => "meta",
            .keyword_q_mins => "mins",
            .keyword_q_mmax => "mmax",
            .keyword_q_mmin => "mmin",
            .keyword_q_mmu => "mmu",
            .keyword_q_mod => "mod",
            .keyword_q_msum => "msum",
            .keyword_q_neg => "neg",
            .keyword_q_next => "next",
            .keyword_q_not => "not",
            .keyword_q_null => "null",
            .keyword_q_or => "or",
            .keyword_q_over => "over",
            .keyword_q_parse => "parse",
            .keyword_q_peach => "peach",
            .keyword_q_pj => "pj",
            .keyword_q_prds => "prds",
            .keyword_q_prev => "prev",
            .keyword_q_prior => "prior",
            .keyword_q_rand => "rand",
            .keyword_q_rank => "rank",
            .keyword_q_ratios => "ratios",
            .keyword_q_raze => "raze",
            .keyword_q_read0 => "read0",
            .keyword_q_read1 => "read1",
            .keyword_q_reciprocal => "reciprocal",
            .keyword_q_reval => "reval",
            .keyword_q_reverse => "reverse",
            .keyword_q_rload => "rload",
            .keyword_q_rotate => "rotate",
            .keyword_q_rsave => "rsave",
            .keyword_q_rtrim => "rtrim",
            .keyword_q_save => "save",
            .keyword_q_scan => "scan",
            .keyword_q_scov => "scov",
            .keyword_q_sdev => "sdev",
            .keyword_q_set => "set",
            .keyword_q_show => "show",
            .keyword_q_signum => "signum",
            .keyword_q_ssr => "ssr",
            .keyword_q_string => "string",
            .keyword_q_sublist => "sublist",
            .keyword_q_sums => "sums",
            .keyword_q_sv => "sv",
            .keyword_q_svar => "svar",
            .keyword_q_system => "system",
            .keyword_q_tables => "tables",
            .keyword_q_til => "til",
            .keyword_q_trim => "trim",
            .keyword_q_type => "type",
            .keyword_q_uj => "uj",
            .keyword_q_ujf => "ujf",
            .keyword_q_ungroup => "ungroup",
            .keyword_q_union => "union",
            .keyword_q_upper => "upper",
            .keyword_q_upsert => "upsert",
            .keyword_q_value => "value",
            .keyword_q_view => "view",
            .keyword_q_views => "views",
            .keyword_q_vs => "vs",
            .keyword_q_where => "where",
            .keyword_q_wj => "wj",
            .keyword_q_wj1 => "wj1",
            .keyword_q_ww => "ww",
            .keyword_q_xasc => "xasc",
            .keyword_q_xbar => "xbar",
            .keyword_q_xcol => "xcol",
            .keyword_q_xcols => "xcols",
            .keyword_q_xdesc => "xdesc",
            .keyword_q_xgroup => "xgroup",
            .keyword_q_xkey => "xkey",
            .keyword_q_xlog => "xlog",
            .keyword_q_xprev => "xprev",
            .keyword_q_xrank => "xrank",
        };
    }

    test "Token tags which have a known lexeme parse as expected" {
        inline for (@typeInfo(Token.Tag).@"enum".fields) |field| {
            const tag: Token.Tag = @enumFromInt(field.value);
            if (tag.lexeme()) |l| {
                const source = try std.testing.allocator.allocSentinel(u8, l.len + 2, 0);
                defer std.testing.allocator.free(source);
                source[0] = '(';
                @memcpy(source[1 .. l.len + 1], l);
                source[l.len + 1] = ')';
                try testTokenize(source, &.{
                    .{ .tag = .l_paren, .loc = .{ .start = 0, .end = 1 }, .eob = false },
                    .{ .tag = tag, .loc = .{ .start = 1, .end = l.len + 1 }, .eob = false },
                    .{ .tag = .r_paren, .loc = .{ .start = l.len + 1, .end = l.len + 2 }, .eob = true },
                });
            }
        }
    }

    pub fn symbol(tag: Tag) []const u8 {
        return tag.lexeme() orelse switch (tag) {
            .number_literal => "a number literal",
            .string_literal => "a string literal",
            .symbol_literal => "a symbol literal",
            .symbol_list_literal => " a symbol list literal",
            .identifier => "an identifier",
            .comment => "a comment",
            .invalid => "invalid bytes",
            .eof => "EOF",
            .os => "an OS command",
            .os_param => "an OS command parameter",
            else => if (builtin.is_test) @panic(@tagName(tag)) else unreachable,
        };
    }

    test "Token tags are not unreachable when calling symbol()" {
        inline for (@typeInfo(Token.Tag).@"enum".fields) |field| {
            const tag: Token.Tag = @enumFromInt(field.value);
            _ = tag.symbol();
        }
    }
};
