const number_parser = @import("../number_parser.zig");
const Parse = @import("../../Parse.zig");
const testNumberParser = number_parser.testNumberParser;
const testNumberParserError = number_parser.testNumberParserError;
const testParse = Parse.testParse;
const null_float = number_parser.null_float;
const inf_float = number_parser.inf_float;

test "valid float inputs" {
    try testNumberParser("0f", .float, @as(f64, 0));
    try testNumberParser("1f", .float, @as(f64, 1));
    try testNumberParser("-1f", .float, @as(f64, -1));
    try testNumberParser(".1f", .float, @as(f64, 0.1));
    try testNumberParser("1.f", .float, @as(f64, 1));
    try testNumberParser("1.1f", .float, @as(f64, 1.1));
    try testNumberParser("-.1f", .float, @as(f64, -0.1));
    try testNumberParser("-1.f", .float, @as(f64, -1));
    try testNumberParser("-1.1f", .float, @as(f64, -1.1));
    try testNumberParser("0Nf", .float, @as(f64, null_float));
    try testNumberParser("0nf", .float, @as(f64, null_float));
    try testNumberParser("0Wf", .float, @as(f64, inf_float));
    try testNumberParser("0wf", .float, @as(f64, inf_float));
    try testNumberParser("-0Wf", .float, @as(f64, -inf_float));
    try testNumberParser("-0wf", .float, @as(f64, -inf_float));

    try testNumberParser(".1", .float, @as(f64, 0.1));
    try testNumberParser("1.", .float, @as(f64, 1));
    try testNumberParser("1.1", .float, @as(f64, 1.1));
    try testNumberParser("-.1", .float, @as(f64, -0.1));
    try testNumberParser("-1.", .float, @as(f64, -1));
    try testNumberParser("-1.1", .float, @as(f64, -1.1));
    try testNumberParser("0n", .float, @as(f64, null_float));
    try testNumberParser("0w", .float, @as(f64, inf_float));
    try testNumberParser("-0w", .float, @as(f64, -inf_float));

    try testParse("1f", &.{ .implicit_return, .float_literal }, "1f");
    try testParse("1.", &.{ .implicit_return, .float_literal }, "1f");
    try testParse("1.f", &.{ .implicit_return, .float_literal }, "1f");
    try testParse("1.1", &.{ .implicit_return, .float_literal }, "1.1");
    try testParse("1.1f", &.{ .implicit_return, .float_literal }, "1.1");
    try testParse("1 2f", &.{ .implicit_return, .float_list_literal }, "1 2f");
    try testParse("1 2.", &.{ .implicit_return, .float_list_literal }, "1 2f");
    try testParse("1 2.f", &.{ .implicit_return, .float_list_literal }, "1 2f");
    try testParse("1 2.2", &.{ .implicit_return, .float_list_literal }, "1 2.2");
    try testParse("1 2.2f", &.{ .implicit_return, .float_list_literal }, "1 2.2");
    try testParse("1. 2", &.{ .implicit_return, .float_list_literal }, "1 2f");
    try testParse("1. 2f", &.{ .implicit_return, .float_list_literal }, "1 2f");
    try testParse("1. 2.", &.{ .implicit_return, .float_list_literal }, "1 2f");
    try testParse("1. 2.f", &.{ .implicit_return, .float_list_literal }, "1 2f");
    try testParse("1. 2.2", &.{ .implicit_return, .float_list_literal }, "1 2.2");
    try testParse("1. 2.2f", &.{ .implicit_return, .float_list_literal }, "1 2.2");
    try testParse("1.1 2", &.{ .implicit_return, .float_list_literal }, "1.1 2");
    try testParse("1.1 2f", &.{ .implicit_return, .float_list_literal }, "1.1 2");
    try testParse("1.1 2.", &.{ .implicit_return, .float_list_literal }, "1.1 2");
    try testParse("1.1 2.f", &.{ .implicit_return, .float_list_literal }, "1.1 2");
    try testParse("1.1 2.2", &.{ .implicit_return, .float_list_literal }, "1.1 2.2");
    try testParse("1.1 2.2f", &.{ .implicit_return, .float_list_literal }, "1.1 2.2");
    try testParse("1 2 3f", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1 2 3.", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1 2 3.f", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1 2 3.3", &.{ .implicit_return, .float_list_literal }, "1 2 3.3");
    try testParse("1 2 3.3f", &.{ .implicit_return, .float_list_literal }, "1 2 3.3");
    try testParse("1 2. 3", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1 2. 3f", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1 2. 3.", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1 2. 3.f", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1 2. 3.3", &.{ .implicit_return, .float_list_literal }, "1 2 3.3");
    try testParse("1 2. 3.3f", &.{ .implicit_return, .float_list_literal }, "1 2 3.3");
    try testParse("1 2.2 3", &.{ .implicit_return, .float_list_literal }, "1 2.2 3");
    try testParse("1 2.2 3f", &.{ .implicit_return, .float_list_literal }, "1 2.2 3");
    try testParse("1 2.2 3.", &.{ .implicit_return, .float_list_literal }, "1 2.2 3");
    try testParse("1 2.2 3.f", &.{ .implicit_return, .float_list_literal }, "1 2.2 3");
    try testParse("1 2.2 3.3", &.{ .implicit_return, .float_list_literal }, "1 2.2 3.3");
    try testParse("1 2.2 3.3f", &.{ .implicit_return, .float_list_literal }, "1 2.2 3.3");
    try testParse("1. 2 3", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1. 2 3f", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1. 2 3.", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1. 2 3.f", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1. 2 3.3", &.{ .implicit_return, .float_list_literal }, "1 2 3.3");
    try testParse("1. 2 3.3f", &.{ .implicit_return, .float_list_literal }, "1 2 3.3");
    try testParse("1. 2. 3", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1. 2. 3f", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1. 2. 3.", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1. 2. 3.f", &.{ .implicit_return, .float_list_literal }, "1 2 3f");
    try testParse("1. 2. 3.3", &.{ .implicit_return, .float_list_literal }, "1 2 3.3");
    try testParse("1. 2. 3.3f", &.{ .implicit_return, .float_list_literal }, "1 2 3.3");
    try testParse("1. 2.2 3", &.{ .implicit_return, .float_list_literal }, "1 2.2 3");
    try testParse("1. 2.2 3f", &.{ .implicit_return, .float_list_literal }, "1 2.2 3");
    try testParse("1. 2.2 3.", &.{ .implicit_return, .float_list_literal }, "1 2.2 3");
    try testParse("1. 2.2 3.f", &.{ .implicit_return, .float_list_literal }, "1 2.2 3");
    try testParse("1. 2.2 3.3", &.{ .implicit_return, .float_list_literal }, "1 2.2 3.3");
    try testParse("1. 2.2 3.3f", &.{ .implicit_return, .float_list_literal }, "1 2.2 3.3");
    try testParse("1.1 2 3", &.{ .implicit_return, .float_list_literal }, "1.1 2 3");
    try testParse("1.1 2 3f", &.{ .implicit_return, .float_list_literal }, "1.1 2 3");
    try testParse("1.1 2 3.", &.{ .implicit_return, .float_list_literal }, "1.1 2 3");
    try testParse("1.1 2 3.f", &.{ .implicit_return, .float_list_literal }, "1.1 2 3");
    try testParse("1.1 2 3.3", &.{ .implicit_return, .float_list_literal }, "1.1 2 3.3");
    try testParse("1.1 2 3.3f", &.{ .implicit_return, .float_list_literal }, "1.1 2 3.3");
    try testParse("1.1 2. 3", &.{ .implicit_return, .float_list_literal }, "1.1 2 3");
    try testParse("1.1 2. 3f", &.{ .implicit_return, .float_list_literal }, "1.1 2 3");
    try testParse("1.1 2. 3.", &.{ .implicit_return, .float_list_literal }, "1.1 2 3");
    try testParse("1.1 2. 3.f", &.{ .implicit_return, .float_list_literal }, "1.1 2 3");
    try testParse("1.1 2. 3.3", &.{ .implicit_return, .float_list_literal }, "1.1 2 3.3");
    try testParse("1.1 2. 3.3f", &.{ .implicit_return, .float_list_literal }, "1.1 2 3.3");
    try testParse("1.1 2.2 3", &.{ .implicit_return, .float_list_literal }, "1.1 2.2 3");
    try testParse("1.1 2.2 3f", &.{ .implicit_return, .float_list_literal }, "1.1 2.2 3");
    try testParse("1.1 2.2 3.", &.{ .implicit_return, .float_list_literal }, "1.1 2.2 3");
    try testParse("1.1 2.2 3.f", &.{ .implicit_return, .float_list_literal }, "1.1 2.2 3");
    try testParse("1.1 2.2 3.3", &.{ .implicit_return, .float_list_literal }, "1.1 2.2 3.3");
    try testParse("1.1 2.2 3.3f", &.{ .implicit_return, .float_list_literal }, "1.1 2.2 3.3");

    try testParse("0Nf", &.{ .implicit_return, .float_literal }, "0n");
    try testParse("0n", &.{ .implicit_return, .float_literal }, "0n");
    try testParse("0nf", &.{ .implicit_return, .float_literal }, "0n");
    try testParse("0Wf", &.{ .implicit_return, .float_literal }, "0w");
    try testParse("0w", &.{ .implicit_return, .float_literal }, "0w");
    try testParse("0wf", &.{ .implicit_return, .float_literal }, "0w");
    try testParse("-0Wf", &.{ .implicit_return, .float_literal }, "-0w");
    try testParse("-0w", &.{ .implicit_return, .float_literal }, "-0w");
    try testParse("-0wf", &.{ .implicit_return, .float_literal }, "-0w");

    try testParse("0N 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0n");
    try testParse("0N 0n", &.{ .implicit_return, .float_list_literal }, "0n 0n");
    try testParse("0N 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0n");
    try testParse("0N 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w");
    try testParse("0N 0w", &.{ .implicit_return, .float_list_literal }, "0n 0w");
    try testParse("0N 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w");
    try testParse("0N -0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w");
    try testParse("0N -0w", &.{ .implicit_return, .float_list_literal }, "0n -0w");
    try testParse("0N -0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w");
    try testParse("0n 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0n");
    try testParse("0n 0n", &.{ .implicit_return, .float_list_literal }, "0n 0n");
    try testParse("0n 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0n");
    try testParse("0n 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w");
    try testParse("0n 0w", &.{ .implicit_return, .float_list_literal }, "0n 0w");
    try testParse("0n 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w");
    try testParse("0n -0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w");
    try testParse("0n -0w", &.{ .implicit_return, .float_list_literal }, "0n -0w");
    try testParse("0n -0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w");
    try testParse("0W 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0n");
    try testParse("0W 0n", &.{ .implicit_return, .float_list_literal }, "0w 0n");
    try testParse("0W 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0n");
    try testParse("0W 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w");
    try testParse("0W 0w", &.{ .implicit_return, .float_list_literal }, "0w 0w");
    try testParse("0W 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w");
    try testParse("0W -0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w");
    try testParse("0W -0w", &.{ .implicit_return, .float_list_literal }, "0w -0w");
    try testParse("0W -0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w");
    try testParse("0w 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0n");
    try testParse("0w 0n", &.{ .implicit_return, .float_list_literal }, "0w 0n");
    try testParse("0w 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0n");
    try testParse("0w 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w");
    try testParse("0w 0w", &.{ .implicit_return, .float_list_literal }, "0w 0w");
    try testParse("0w 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w");
    try testParse("0w -0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w");
    try testParse("0w -0w", &.{ .implicit_return, .float_list_literal }, "0w -0w");
    try testParse("0w -0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w");
    try testParse("-0W 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n");
    try testParse("-0W 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0n");
    try testParse("-0W 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n");
    try testParse("-0W 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w");
    try testParse("-0W 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w");
    try testParse("-0W 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w");
    try testParse("-0W -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w");
    try testParse("-0W -0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w");
    try testParse("-0W -0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w");
    try testParse("-0w 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n");
    try testParse("-0w 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0n");
    try testParse("-0w 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n");
    try testParse("-0w 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w");
    try testParse("-0w 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w");
    try testParse("-0w 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w");
    try testParse("-0w -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w");
    try testParse("-0w -0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w");
    try testParse("-0w -0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w");

    try testParse("0N 0N 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0N 0N 0n", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0N 0N 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0N 0N 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0N 0N 0w", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0N 0N 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0N 0N -0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0N 0N -0w", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0N 0N -0wf", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0N 0n 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0N 0n 0n", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0N 0n 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0N 0n 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0N 0n 0w", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0N 0n 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0N 0n -0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0N 0n -0w", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0N 0n -0wf", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0N 0W 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0N 0W 0n", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0N 0W 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0N 0W 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0N 0W 0w", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0N 0W 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0N 0W -0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0N 0W -0w", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0N 0W -0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0N 0w 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0N 0w 0n", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0N 0w 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0N 0w 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0N 0w 0w", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0N 0w 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0N 0w -0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0N 0w -0w", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0N 0w -0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0N -0W 0Nf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0N -0W 0n", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0N -0W 0nf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0N -0W 0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0N -0W 0w", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0N -0W 0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0N -0W -0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0N -0W -0w", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0N -0W -0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0N -0w 0Nf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0N -0w 0n", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0N -0w 0nf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0N -0w 0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0N -0w 0w", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0N -0w 0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0N -0w -0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0N -0w -0w", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0N -0w -0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0n 0N 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0n 0N 0n", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0n 0N 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0n 0N 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0n 0N 0w", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0n 0N 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0n 0N -0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0n 0N -0w", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0n 0N -0wf", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0n 0n 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0n 0n 0n", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0n 0n 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0n");
    try testParse("0n 0n 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0n 0n 0w", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0n 0n 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0n 0w");
    try testParse("0n 0n -0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0n 0n -0w", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0n 0n -0wf", &.{ .implicit_return, .float_list_literal }, "0n 0n -0w");
    try testParse("0n 0W 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0n 0W 0n", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0n 0W 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0n 0W 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0n 0W 0w", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0n 0W 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0n 0W -0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0n 0W -0w", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0n 0W -0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0n 0w 0Nf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0n 0w 0n", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0n 0w 0nf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0n");
    try testParse("0n 0w 0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0n 0w 0w", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0n 0w 0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w 0w");
    try testParse("0n 0w -0Wf", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0n 0w -0w", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0n 0w -0wf", &.{ .implicit_return, .float_list_literal }, "0n 0w -0w");
    try testParse("0n -0W 0Nf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0n -0W 0n", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0n -0W 0nf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0n -0W 0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0n -0W 0w", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0n -0W 0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0n -0W -0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0n -0W -0w", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0n -0W -0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0n -0w 0Nf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0n -0w 0n", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0n -0w 0nf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0n");
    try testParse("0n -0w 0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0n -0w 0w", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0n -0w 0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w 0w");
    try testParse("0n -0w -0Wf", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0n -0w -0w", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0n -0w -0wf", &.{ .implicit_return, .float_list_literal }, "0n -0w -0w");
    try testParse("0W 0N 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0W 0N 0n", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0W 0N 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0W 0N 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0W 0N 0w", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0W 0N 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0W 0N -0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0W 0N -0w", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0W 0N -0wf", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0W 0n 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0W 0n 0n", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0W 0n 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0W 0n 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0W 0n 0w", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0W 0n 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0W 0n -0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0W 0n -0w", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0W 0n -0wf", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0W 0W 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0W 0W 0n", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0W 0W 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0W 0W 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0W 0W 0w", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0W 0W 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0W 0W -0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0W 0W -0w", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0W 0W -0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0W 0w 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0W 0w 0n", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0W 0w 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0W 0w 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0W 0w 0w", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0W 0w 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0W 0w -0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0W 0w -0w", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0W 0w -0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0W -0W 0Nf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0W -0W 0n", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0W -0W 0nf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0W -0W 0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0W -0W 0w", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0W -0W 0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0W -0W -0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0W -0W -0w", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0W -0W -0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0W -0w 0Nf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0W -0w 0n", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0W -0w 0nf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0W -0w 0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0W -0w 0w", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0W -0w 0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0W -0w -0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0W -0w -0w", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0W -0w -0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0w 0N 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0w 0N 0n", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0w 0N 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0w 0N 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0w 0N 0w", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0w 0N 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0w 0N -0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0w 0N -0w", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0w 0N -0wf", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0w 0n 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0w 0n 0n", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0w 0n 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0n");
    try testParse("0w 0n 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0w 0n 0w", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0w 0n 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0n 0w");
    try testParse("0w 0n -0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0w 0n -0w", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0w 0n -0wf", &.{ .implicit_return, .float_list_literal }, "0w 0n -0w");
    try testParse("0w 0W 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0w 0W 0n", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0w 0W 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0w 0W 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0w 0W 0w", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0w 0W 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0w 0W -0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0w 0W -0w", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0w 0W -0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0w 0w 0Nf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0w 0w 0n", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0w 0w 0nf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0n");
    try testParse("0w 0w 0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0w 0w 0w", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0w 0w 0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w 0w");
    try testParse("0w 0w -0Wf", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0w 0w -0w", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0w 0w -0wf", &.{ .implicit_return, .float_list_literal }, "0w 0w -0w");
    try testParse("0w -0W 0Nf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0w -0W 0n", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0w -0W 0nf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0w -0W 0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0w -0W 0w", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0w -0W 0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0w -0W -0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0w -0W -0w", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0w -0W -0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0w -0w 0Nf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0w -0w 0n", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0w -0w 0nf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0n");
    try testParse("0w -0w 0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0w -0w 0w", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0w -0w 0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w 0w");
    try testParse("0w -0w -0Wf", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0w -0w -0w", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("0w -0w -0wf", &.{ .implicit_return, .float_list_literal }, "0w -0w -0w");
    try testParse("-0W 0N 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0W 0N 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0W 0N 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0W 0N 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0W 0N 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0W 0N 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0W 0N -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0W 0N -0w", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0W 0N -0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0W 0n 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0W 0n 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0W 0n 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0W 0n 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0W 0n 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0W 0n 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0W 0n -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0W 0n -0w", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0W 0n -0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0W 0W 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0W 0W 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0W 0W 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0W 0W 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0W 0W 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0W 0W 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0W 0W -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0W 0W -0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0W 0W -0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0W 0w 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0W 0w 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0W 0w 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0W 0w 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0W 0w 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0W 0w 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0W 0w -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0W 0w -0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0W 0w -0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0W -0W 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0W -0W 0n", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0W -0W 0nf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0W -0W 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0W -0W 0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0W -0W 0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0W -0W -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0W -0W -0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0W -0W -0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0W -0w 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0W -0w 0n", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0W -0w 0nf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0W -0w 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0W -0w 0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0W -0w 0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0W -0w -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0W -0w -0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0W -0w -0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0w 0N 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0w 0N 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0w 0N 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0w 0N 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0w 0N 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0w 0N 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0w 0N -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0w 0N -0w", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0w 0N -0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0w 0n 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0w 0n 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0w 0n 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0n");
    try testParse("-0w 0n 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0w 0n 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0w 0n 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n 0w");
    try testParse("-0w 0n -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0w 0n -0w", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0w 0n -0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0n -0w");
    try testParse("-0w 0W 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0w 0W 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0w 0W 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0w 0W 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0w 0W 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0w 0W 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0w 0W -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0w 0W -0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0w 0W -0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0w 0w 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0w 0w 0n", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0w 0w 0nf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0n");
    try testParse("-0w 0w 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0w 0w 0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0w 0w 0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w 0w");
    try testParse("-0w 0w -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0w 0w -0w", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0w 0w -0wf", &.{ .implicit_return, .float_list_literal }, "-0w 0w -0w");
    try testParse("-0w -0W 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0w -0W 0n", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0w -0W 0nf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0w -0W 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0w -0W 0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0w -0W 0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0w -0W -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0w -0W -0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0w -0W -0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0w -0w 0Nf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0w -0w 0n", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0w -0w 0nf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0n");
    try testParse("-0w -0w 0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0w -0w 0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0w -0w 0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w 0w");
    try testParse("-0w -0w -0Wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0w -0w -0w", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
    try testParse("-0w -0w -0wf", &.{ .implicit_return, .float_list_literal }, "-0w -0w -0w");
}

test "invalid float inputs" {
    try testNumberParserError("0ff", error.InvalidCharacter);
    try testNumberParserError("1ff", error.InvalidCharacter);
    try testNumberParserError("-1ff", error.InvalidCharacter);
    try testNumberParserError(".1ff", error.InvalidCharacter);
    try testNumberParserError("1.ff", error.InvalidCharacter);
    try testNumberParserError("1.1ff", error.InvalidCharacter);
    try testNumberParserError("-.1ff", error.InvalidCharacter);
    try testNumberParserError("-1.ff", error.InvalidCharacter);
    try testNumberParserError("-1.1ff", error.InvalidCharacter);
}

test "float scientific notation" {
    return error.SkipZigTest;
}

test {
    @import("std").testing.refAllDecls(@This());
}
