const number_parser = @import("../number_parser.zig");
const Parse = @import("../../Parse.zig");
const testNumberParser = number_parser.testNumberParser;
const testNumberParserError = number_parser.testNumberParserError;
const testParse = Parse.testParse;
const testParseError = Parse.testParseError;
const null_int = number_parser.null_int;
const inf_int = number_parser.inf_int;

test "valid int inputs" {
    try testNumberParser("0i", .int, 0);
    try testNumberParser("1i", .int, 1);
    try testNumberParser("-1i", .int, -1);
    try testNumberParser("2147483646i", .int, 2147483646);
    try testNumberParser("-2147483646i", .int, -2147483646);
    try testNumberParser("0Ni", .int, null_int);
    try testNumberParser("0ni", .int, null_int);
    try testNumberParser("0Wi", .int, inf_int);
    try testNumberParser("0wi", .int, inf_int);
    try testNumberParser("2147483647i", .int, inf_int);
    try testNumberParser("-0Wi", .int, -inf_int);
    try testNumberParser("-0wi", .int, -inf_int);
    try testNumberParser("-2147483647i", .int, -inf_int);

    try testParse("1i", &.{ .implicit_return, .int_literal }, "1i");
    try testParse("1 2i", &.{ .implicit_return, .int_list_literal }, "1 2i");
    try testParse("1 2 3i", &.{ .implicit_return, .int_list_literal }, "1 2 3i");

    try testParse("0Ni", &.{ .implicit_return, .int_literal }, "0Ni");
    try testParse("0ni", &.{ .implicit_return, .int_literal }, "0Ni");
    try testParse("0Wi", &.{ .implicit_return, .int_literal }, "0Wi");
    try testParse("0wi", &.{ .implicit_return, .int_literal }, "0Wi");
    try testParse("-0Wi", &.{ .implicit_return, .int_literal }, "-0Wi");
    try testParse("-0wi", &.{ .implicit_return, .int_literal }, "-0Wi");

    try testParse("0N 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0Ni");
    try testParse("0N 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0Ni");
    try testParse("0N 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0Wi");
    try testParse("0N 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0Wi");
    try testParse("0N -0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0Wi");
    try testParse("0N -0wi", &.{ .implicit_return, .int_list_literal }, "0N -0Wi");
    try testParse("0n 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0Ni");
    try testParse("0n 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0Ni");
    try testParse("0n 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0Wi");
    try testParse("0n 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0Wi");
    try testParse("0n -0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0Wi");
    try testParse("0n -0wi", &.{ .implicit_return, .int_list_literal }, "0N -0Wi");
    try testParse("0W 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0Ni");
    try testParse("0W 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0Ni");
    try testParse("0W 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0Wi");
    try testParse("0W 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0Wi");
    try testParse("0W -0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0Wi");
    try testParse("0W -0wi", &.{ .implicit_return, .int_list_literal }, "0W -0Wi");
    try testParse("0w 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0Ni");
    try testParse("0w 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0Ni");
    try testParse("0w 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0Wi");
    try testParse("0w 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0Wi");
    try testParse("0w -0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0Wi");
    try testParse("0w -0wi", &.{ .implicit_return, .int_list_literal }, "0W -0Wi");
    try testParse("-0W 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0Ni");
    try testParse("-0W 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0Ni");
    try testParse("-0W 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0Wi");
    try testParse("-0W 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0Wi");
    try testParse("-0W -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0Wi");
    try testParse("-0W -0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0Wi");
    try testParse("-0w 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0Ni");
    try testParse("-0w 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0Ni");
    try testParse("-0w 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0Wi");
    try testParse("-0w 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0Wi");
    try testParse("-0w -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0Wi");
    try testParse("-0w -0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0Wi");

    try testParse("0N 0N 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Ni");
    try testParse("0N 0N 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Ni");
    try testParse("0N 0N 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Wi");
    try testParse("0N 0N 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Wi");
    try testParse("0N 0N -0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0N -0Wi");
    try testParse("0N 0N -0wi", &.{ .implicit_return, .int_list_literal }, "0N 0N -0Wi");
    try testParse("0N 0n 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Ni");
    try testParse("0N 0n 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Ni");
    try testParse("0N 0n 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Wi");
    try testParse("0N 0n 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Wi");
    try testParse("0N 0n -0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0N -0Wi");
    try testParse("0N 0n -0wi", &.{ .implicit_return, .int_list_literal }, "0N 0N -0Wi");
    try testParse("0N 0W 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Ni");
    try testParse("0N 0W 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Ni");
    try testParse("0N 0W 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Wi");
    try testParse("0N 0W 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Wi");
    try testParse("0N 0W -0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0W -0Wi");
    try testParse("0N 0W -0wi", &.{ .implicit_return, .int_list_literal }, "0N 0W -0Wi");
    try testParse("0N 0w 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Ni");
    try testParse("0N 0w 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Ni");
    try testParse("0N 0w 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Wi");
    try testParse("0N 0w 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Wi");
    try testParse("0N 0w -0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0W -0Wi");
    try testParse("0N 0w -0wi", &.{ .implicit_return, .int_list_literal }, "0N 0W -0Wi");
    try testParse("0N -0W 0Ni", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Ni");
    try testParse("0N -0W 0ni", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Ni");
    try testParse("0N -0W 0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Wi");
    try testParse("0N -0W 0wi", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Wi");
    try testParse("0N -0W -0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0W -0Wi");
    try testParse("0N -0W -0wi", &.{ .implicit_return, .int_list_literal }, "0N -0W -0Wi");
    try testParse("0N -0w 0Ni", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Ni");
    try testParse("0N -0w 0ni", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Ni");
    try testParse("0N -0w 0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Wi");
    try testParse("0N -0w 0wi", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Wi");
    try testParse("0N -0w -0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0W -0Wi");
    try testParse("0N -0w -0wi", &.{ .implicit_return, .int_list_literal }, "0N -0W -0Wi");
    try testParse("0n 0N 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Ni");
    try testParse("0n 0N 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Ni");
    try testParse("0n 0N 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Wi");
    try testParse("0n 0N 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Wi");
    try testParse("0n 0N -0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0N -0Wi");
    try testParse("0n 0N -0wi", &.{ .implicit_return, .int_list_literal }, "0N 0N -0Wi");
    try testParse("0n 0n 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Ni");
    try testParse("0n 0n 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Ni");
    try testParse("0n 0n 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Wi");
    try testParse("0n 0n 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0N 0Wi");
    try testParse("0n 0n -0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0N -0Wi");
    try testParse("0n 0n -0wi", &.{ .implicit_return, .int_list_literal }, "0N 0N -0Wi");
    try testParse("0n 0W 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Ni");
    try testParse("0n 0W 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Ni");
    try testParse("0n 0W 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Wi");
    try testParse("0n 0W 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Wi");
    try testParse("0n 0W -0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0W -0Wi");
    try testParse("0n 0W -0wi", &.{ .implicit_return, .int_list_literal }, "0N 0W -0Wi");
    try testParse("0n 0w 0Ni", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Ni");
    try testParse("0n 0w 0ni", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Ni");
    try testParse("0n 0w 0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Wi");
    try testParse("0n 0w 0wi", &.{ .implicit_return, .int_list_literal }, "0N 0W 0Wi");
    try testParse("0n 0w -0Wi", &.{ .implicit_return, .int_list_literal }, "0N 0W -0Wi");
    try testParse("0n 0w -0wi", &.{ .implicit_return, .int_list_literal }, "0N 0W -0Wi");
    try testParse("0n -0W 0Ni", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Ni");
    try testParse("0n -0W 0ni", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Ni");
    try testParse("0n -0W 0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Wi");
    try testParse("0n -0W 0wi", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Wi");
    try testParse("0n -0W -0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0W -0Wi");
    try testParse("0n -0W -0wi", &.{ .implicit_return, .int_list_literal }, "0N -0W -0Wi");
    try testParse("0n -0w 0Ni", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Ni");
    try testParse("0n -0w 0ni", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Ni");
    try testParse("0n -0w 0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Wi");
    try testParse("0n -0w 0wi", &.{ .implicit_return, .int_list_literal }, "0N -0W 0Wi");
    try testParse("0n -0w -0Wi", &.{ .implicit_return, .int_list_literal }, "0N -0W -0Wi");
    try testParse("0n -0w -0wi", &.{ .implicit_return, .int_list_literal }, "0N -0W -0Wi");
    try testParse("0W 0N 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Ni");
    try testParse("0W 0N 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Ni");
    try testParse("0W 0N 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Wi");
    try testParse("0W 0N 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Wi");
    try testParse("0W 0N -0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0N -0Wi");
    try testParse("0W 0N -0wi", &.{ .implicit_return, .int_list_literal }, "0W 0N -0Wi");
    try testParse("0W 0n 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Ni");
    try testParse("0W 0n 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Ni");
    try testParse("0W 0n 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Wi");
    try testParse("0W 0n 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Wi");
    try testParse("0W 0n -0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0N -0Wi");
    try testParse("0W 0n -0wi", &.{ .implicit_return, .int_list_literal }, "0W 0N -0Wi");
    try testParse("0W 0W 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Ni");
    try testParse("0W 0W 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Ni");
    try testParse("0W 0W 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Wi");
    try testParse("0W 0W 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Wi");
    try testParse("0W 0W -0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0W -0Wi");
    try testParse("0W 0W -0wi", &.{ .implicit_return, .int_list_literal }, "0W 0W -0Wi");
    try testParse("0W 0w 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Ni");
    try testParse("0W 0w 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Ni");
    try testParse("0W 0w 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Wi");
    try testParse("0W 0w 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Wi");
    try testParse("0W 0w -0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0W -0Wi");
    try testParse("0W 0w -0wi", &.{ .implicit_return, .int_list_literal }, "0W 0W -0Wi");
    try testParse("0W -0W 0Ni", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Ni");
    try testParse("0W -0W 0ni", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Ni");
    try testParse("0W -0W 0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Wi");
    try testParse("0W -0W 0wi", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Wi");
    try testParse("0W -0W -0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0W -0Wi");
    try testParse("0W -0W -0wi", &.{ .implicit_return, .int_list_literal }, "0W -0W -0Wi");
    try testParse("0W -0w 0Ni", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Ni");
    try testParse("0W -0w 0ni", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Ni");
    try testParse("0W -0w 0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Wi");
    try testParse("0W -0w 0wi", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Wi");
    try testParse("0W -0w -0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0W -0Wi");
    try testParse("0W -0w -0wi", &.{ .implicit_return, .int_list_literal }, "0W -0W -0Wi");
    try testParse("0w 0N 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Ni");
    try testParse("0w 0N 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Ni");
    try testParse("0w 0N 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Wi");
    try testParse("0w 0N 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Wi");
    try testParse("0w 0N -0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0N -0Wi");
    try testParse("0w 0N -0wi", &.{ .implicit_return, .int_list_literal }, "0W 0N -0Wi");
    try testParse("0w 0n 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Ni");
    try testParse("0w 0n 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Ni");
    try testParse("0w 0n 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Wi");
    try testParse("0w 0n 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0N 0Wi");
    try testParse("0w 0n -0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0N -0Wi");
    try testParse("0w 0n -0wi", &.{ .implicit_return, .int_list_literal }, "0W 0N -0Wi");
    try testParse("0w 0W 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Ni");
    try testParse("0w 0W 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Ni");
    try testParse("0w 0W 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Wi");
    try testParse("0w 0W 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Wi");
    try testParse("0w 0W -0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0W -0Wi");
    try testParse("0w 0W -0wi", &.{ .implicit_return, .int_list_literal }, "0W 0W -0Wi");
    try testParse("0w 0w 0Ni", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Ni");
    try testParse("0w 0w 0ni", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Ni");
    try testParse("0w 0w 0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Wi");
    try testParse("0w 0w 0wi", &.{ .implicit_return, .int_list_literal }, "0W 0W 0Wi");
    try testParse("0w 0w -0Wi", &.{ .implicit_return, .int_list_literal }, "0W 0W -0Wi");
    try testParse("0w 0w -0wi", &.{ .implicit_return, .int_list_literal }, "0W 0W -0Wi");
    try testParse("0w -0W 0Ni", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Ni");
    try testParse("0w -0W 0ni", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Ni");
    try testParse("0w -0W 0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Wi");
    try testParse("0w -0W 0wi", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Wi");
    try testParse("0w -0W -0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0W -0Wi");
    try testParse("0w -0W -0wi", &.{ .implicit_return, .int_list_literal }, "0W -0W -0Wi");
    try testParse("0w -0w 0Ni", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Ni");
    try testParse("0w -0w 0ni", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Ni");
    try testParse("0w -0w 0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Wi");
    try testParse("0w -0w 0wi", &.{ .implicit_return, .int_list_literal }, "0W -0W 0Wi");
    try testParse("0w -0w -0Wi", &.{ .implicit_return, .int_list_literal }, "0W -0W -0Wi");
    try testParse("0w -0w -0wi", &.{ .implicit_return, .int_list_literal }, "0W -0W -0Wi");
    try testParse("-0W 0N 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Ni");
    try testParse("-0W 0N 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Ni");
    try testParse("-0W 0N 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Wi");
    try testParse("-0W 0N 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Wi");
    try testParse("-0W 0N -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N -0Wi");
    try testParse("-0W 0N -0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N -0Wi");
    try testParse("-0W 0n 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Ni");
    try testParse("-0W 0n 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Ni");
    try testParse("-0W 0n 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Wi");
    try testParse("-0W 0n 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Wi");
    try testParse("-0W 0n -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N -0Wi");
    try testParse("-0W 0n -0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N -0Wi");
    try testParse("-0W 0W 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Ni");
    try testParse("-0W 0W 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Ni");
    try testParse("-0W 0W 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Wi");
    try testParse("-0W 0W 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Wi");
    try testParse("-0W 0W -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W -0Wi");
    try testParse("-0W 0W -0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W -0Wi");
    try testParse("-0W 0w 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Ni");
    try testParse("-0W 0w 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Ni");
    try testParse("-0W 0w 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Wi");
    try testParse("-0W 0w 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Wi");
    try testParse("-0W 0w -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W -0Wi");
    try testParse("-0W 0w -0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W -0Wi");
    try testParse("-0W -0W 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Ni");
    try testParse("-0W -0W 0ni", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Ni");
    try testParse("-0W -0W 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Wi");
    try testParse("-0W -0W 0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Wi");
    try testParse("-0W -0W -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W -0Wi");
    try testParse("-0W -0W -0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W -0Wi");
    try testParse("-0W -0w 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Ni");
    try testParse("-0W -0w 0ni", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Ni");
    try testParse("-0W -0w 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Wi");
    try testParse("-0W -0w 0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Wi");
    try testParse("-0W -0w -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W -0Wi");
    try testParse("-0W -0w -0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W -0Wi");
    try testParse("-0w 0N 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Ni");
    try testParse("-0w 0N 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Ni");
    try testParse("-0w 0N 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Wi");
    try testParse("-0w 0N 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Wi");
    try testParse("-0w 0N -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N -0Wi");
    try testParse("-0w 0N -0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N -0Wi");
    try testParse("-0w 0n 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Ni");
    try testParse("-0w 0n 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Ni");
    try testParse("-0w 0n 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Wi");
    try testParse("-0w 0n 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N 0Wi");
    try testParse("-0w 0n -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N -0Wi");
    try testParse("-0w 0n -0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0N -0Wi");
    try testParse("-0w 0W 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Ni");
    try testParse("-0w 0W 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Ni");
    try testParse("-0w 0W 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Wi");
    try testParse("-0w 0W 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Wi");
    try testParse("-0w 0W -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W -0Wi");
    try testParse("-0w 0W -0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W -0Wi");
    try testParse("-0w 0w 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Ni");
    try testParse("-0w 0w 0ni", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Ni");
    try testParse("-0w 0w 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Wi");
    try testParse("-0w 0w 0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W 0Wi");
    try testParse("-0w 0w -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W -0Wi");
    try testParse("-0w 0w -0wi", &.{ .implicit_return, .int_list_literal }, "-0W 0W -0Wi");
    try testParse("-0w -0W 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Ni");
    try testParse("-0w -0W 0ni", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Ni");
    try testParse("-0w -0W 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Wi");
    try testParse("-0w -0W 0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Wi");
    try testParse("-0w -0W -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W -0Wi");
    try testParse("-0w -0W -0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W -0Wi");
    try testParse("-0w -0w 0Ni", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Ni");
    try testParse("-0w -0w 0ni", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Ni");
    try testParse("-0w -0w 0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Wi");
    try testParse("-0w -0w 0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W 0Wi");
    try testParse("-0w -0w -0Wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W -0Wi");
    try testParse("-0w -0w -0wi", &.{ .implicit_return, .int_list_literal }, "-0W -0W -0Wi");
}

test "invalid int inputs" {
    try testNumberParserError("0ii", error.InvalidCharacter);
    try testNumberParserError("1ii", error.InvalidCharacter);
    try testNumberParserError("-1ii", error.InvalidCharacter);
    try testNumberParserError("2147483646ii", error.InvalidCharacter);
    try testNumberParserError("-2147483646ii", error.InvalidCharacter);
    try testNumberParserError(".1i", error.InvalidCharacter);
    try testNumberParserError("1.i", error.InvalidCharacter);
    try testNumberParserError("1.1i", error.InvalidCharacter);
    try testNumberParserError("2147483648i", error.Overflow);
    try testNumberParserError("-2147483648i", error.Overflow);
    try testNumberParserError("-2147483649i", error.Overflow);

    try testParseError("1. 2i", &.{.parse_error});
    try testParseError("1. 2. 3i", &.{.parse_error});
}
