const number_parser = @import("../number_parser.zig");
const Parse = @import("../../Parse.zig");
const testNumberParser = number_parser.testNumberParser;
const testNumberParserError = number_parser.testNumberParserError;
const testParse = Parse.testParse;
const testParseError = Parse.testParseError;
const null_long = number_parser.null_long;
const inf_long = number_parser.inf_long;

test "valid long inputs" {
    try testNumberParser("0j", .long, 0);
    try testNumberParser("1j", .long, 1);
    try testNumberParser("-1j", .long, -1);
    try testNumberParser("9223372036854775806j", .long, 9223372036854775806);
    try testNumberParser("-9223372036854775806j", .long, -9223372036854775806);
    try testNumberParser("0Nj", .long, null_long);
    try testNumberParser("0nj", .long, null_long);
    try testNumberParser("0Wj", .long, inf_long);
    try testNumberParser("0wj", .long, inf_long);
    try testNumberParser("9223372036854775807j", .long, inf_long);
    try testNumberParser("-0Wj", .long, -inf_long);
    try testNumberParser("-0wj", .long, -inf_long);
    try testNumberParser("-9223372036854775807j", .long, -inf_long);

    try testNumberParser("0", .long, 0);
    try testNumberParser("1", .long, 1);
    try testNumberParser("-1", .long, -1);
    try testNumberParser("9223372036854775806", .long, 9223372036854775806);
    try testNumberParser("-9223372036854775806", .long, -9223372036854775806);
    try testNumberParser("0N", .long, null_long);
    try testNumberParser("0W", .long, inf_long);
    try testNumberParser("9223372036854775807", .long, inf_long);
    try testNumberParser("-0W", .long, -inf_long);
    try testNumberParser("-9223372036854775807", .long, -inf_long);

    try testParse("1", &.{ .implicit_return, .long_literal }, "1");
    try testParse("1j", &.{ .implicit_return, .long_literal }, "1");
    try testParse("1 2", &.{ .implicit_return, .long_list_literal }, "1 2");
    try testParse("1 2j", &.{ .implicit_return, .long_list_literal }, "1 2");
    try testParse("1 2 3", &.{ .implicit_return, .long_list_literal }, "1 2 3");
    try testParse("1 2 3j", &.{ .implicit_return, .long_list_literal }, "1 2 3");

    try testParse("0N", &.{ .implicit_return, .long_literal }, "0N");
    try testParse("0Nj", &.{ .implicit_return, .long_literal }, "0N");
    try testParse("0nj", &.{ .implicit_return, .long_literal }, "0N");
    try testParse("0W", &.{ .implicit_return, .long_literal }, "0W");
    try testParse("0Wj", &.{ .implicit_return, .long_literal }, "0W");
    try testParse("0wj", &.{ .implicit_return, .long_literal }, "0W");
    try testParse("-0W", &.{ .implicit_return, .long_literal }, "-0W");
    try testParse("-0Wj", &.{ .implicit_return, .long_literal }, "-0W");
    try testParse("-0wj", &.{ .implicit_return, .long_literal }, "-0W");

    try testParse("0N 0N", &.{ .implicit_return, .long_list_literal }, "0N 0N");
    try testParse("0N 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0N");
    try testParse("0N 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0N");
    try testParse("0N 0W", &.{ .implicit_return, .long_list_literal }, "0N 0W");
    try testParse("0N 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W");
    try testParse("0N 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W");
    try testParse("0N -0W", &.{ .implicit_return, .long_list_literal }, "0N -0W");
    try testParse("0N -0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W");
    try testParse("0N -0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W");
    try testParse("0n 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0N");
    try testParse("0n 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0N");
    try testParse("0n 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W");
    try testParse("0n 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W");
    try testParse("0n -0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W");
    try testParse("0n -0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W");
    try testParse("0W 0N", &.{ .implicit_return, .long_list_literal }, "0W 0N");
    try testParse("0W 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0N");
    try testParse("0W 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0N");
    try testParse("0W 0W", &.{ .implicit_return, .long_list_literal }, "0W 0W");
    try testParse("0W 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W");
    try testParse("0W 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W");
    try testParse("0W -0W", &.{ .implicit_return, .long_list_literal }, "0W -0W");
    try testParse("0W -0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W");
    try testParse("0W -0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W");
    try testParse("0w 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0N");
    try testParse("0w 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0N");
    try testParse("0w 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W");
    try testParse("0w 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W");
    try testParse("0w -0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W");
    try testParse("0w -0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W");
    try testParse("-0W 0N", &.{ .implicit_return, .long_list_literal }, "-0W 0N");
    try testParse("-0W 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N");
    try testParse("-0W 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N");
    try testParse("-0W 0W", &.{ .implicit_return, .long_list_literal }, "-0W 0W");
    try testParse("-0W 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W");
    try testParse("-0W 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W");
    try testParse("-0W -0W", &.{ .implicit_return, .long_list_literal }, "-0W -0W");
    try testParse("-0W -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W");
    try testParse("-0W -0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W");
    try testParse("-0w 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N");
    try testParse("-0w 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N");
    try testParse("-0w 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W");
    try testParse("-0w 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W");
    try testParse("-0w -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W");
    try testParse("-0w -0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W");

    try testParse("0N 0N 0N", &.{ .implicit_return, .long_list_literal }, "0N 0N 0N");
    try testParse("0N 0N 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0N");
    try testParse("0N 0N 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0N");
    try testParse("0N 0N 0W", &.{ .implicit_return, .long_list_literal }, "0N 0N 0W");
    try testParse("0N 0N 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0W");
    try testParse("0N 0N 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0W");
    try testParse("0N 0N -0W", &.{ .implicit_return, .long_list_literal }, "0N 0N -0W");
    try testParse("0N 0N -0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0N -0W");
    try testParse("0N 0N -0wj", &.{ .implicit_return, .long_list_literal }, "0N 0N -0W");
    try testParse("0N 0n 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0N");
    try testParse("0N 0n 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0N");
    try testParse("0N 0n 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0W");
    try testParse("0N 0n 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0W");
    try testParse("0N 0n -0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0N -0W");
    try testParse("0N 0n -0wj", &.{ .implicit_return, .long_list_literal }, "0N 0N -0W");
    try testParse("0N 0W 0N", &.{ .implicit_return, .long_list_literal }, "0N 0W 0N");
    try testParse("0N 0W 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0N");
    try testParse("0N 0W 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0N");
    try testParse("0N 0W 0W", &.{ .implicit_return, .long_list_literal }, "0N 0W 0W");
    try testParse("0N 0W 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0W");
    try testParse("0N 0W 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0W");
    try testParse("0N 0W -0W", &.{ .implicit_return, .long_list_literal }, "0N 0W -0W");
    try testParse("0N 0W -0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W -0W");
    try testParse("0N 0W -0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W -0W");
    try testParse("0N 0w 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0N");
    try testParse("0N 0w 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0N");
    try testParse("0N 0w 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0W");
    try testParse("0N 0w 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0W");
    try testParse("0N 0w -0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W -0W");
    try testParse("0N 0w -0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W -0W");
    try testParse("0N -0W 0N", &.{ .implicit_return, .long_list_literal }, "0N -0W 0N");
    try testParse("0N -0W 0Nj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0N");
    try testParse("0N -0W 0nj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0N");
    try testParse("0N -0W 0W", &.{ .implicit_return, .long_list_literal }, "0N -0W 0W");
    try testParse("0N -0W 0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0W");
    try testParse("0N -0W 0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0W");
    try testParse("0N -0W -0W", &.{ .implicit_return, .long_list_literal }, "0N -0W -0W");
    try testParse("0N -0W -0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W -0W");
    try testParse("0N -0W -0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W -0W");
    try testParse("0N -0w 0Nj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0N");
    try testParse("0N -0w 0nj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0N");
    try testParse("0N -0w 0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0W");
    try testParse("0N -0w 0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0W");
    try testParse("0N -0w -0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W -0W");
    try testParse("0N -0w -0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W -0W");
    try testParse("0n 0N 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0N");
    try testParse("0n 0N 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0N");
    try testParse("0n 0N 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0W");
    try testParse("0n 0N 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0W");
    try testParse("0n 0N -0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0N -0W");
    try testParse("0n 0N -0wj", &.{ .implicit_return, .long_list_literal }, "0N 0N -0W");
    try testParse("0n 0n 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0N");
    try testParse("0n 0n 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0N");
    try testParse("0n 0n 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0W");
    try testParse("0n 0n 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0N 0W");
    try testParse("0n 0n -0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0N -0W");
    try testParse("0n 0n -0wj", &.{ .implicit_return, .long_list_literal }, "0N 0N -0W");
    try testParse("0n 0W 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0N");
    try testParse("0n 0W 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0N");
    try testParse("0n 0W 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0W");
    try testParse("0n 0W 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0W");
    try testParse("0n 0W -0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W -0W");
    try testParse("0n 0W -0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W -0W");
    try testParse("0n 0w 0Nj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0N");
    try testParse("0n 0w 0nj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0N");
    try testParse("0n 0w 0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0W");
    try testParse("0n 0w 0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W 0W");
    try testParse("0n 0w -0Wj", &.{ .implicit_return, .long_list_literal }, "0N 0W -0W");
    try testParse("0n 0w -0wj", &.{ .implicit_return, .long_list_literal }, "0N 0W -0W");
    try testParse("0n -0W 0Nj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0N");
    try testParse("0n -0W 0nj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0N");
    try testParse("0n -0W 0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0W");
    try testParse("0n -0W 0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0W");
    try testParse("0n -0W -0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W -0W");
    try testParse("0n -0W -0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W -0W");
    try testParse("0n -0w 0Nj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0N");
    try testParse("0n -0w 0nj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0N");
    try testParse("0n -0w 0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0W");
    try testParse("0n -0w 0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W 0W");
    try testParse("0n -0w -0Wj", &.{ .implicit_return, .long_list_literal }, "0N -0W -0W");
    try testParse("0n -0w -0wj", &.{ .implicit_return, .long_list_literal }, "0N -0W -0W");
    try testParse("0W 0N 0N", &.{ .implicit_return, .long_list_literal }, "0W 0N 0N");
    try testParse("0W 0N 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0N");
    try testParse("0W 0N 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0N");
    try testParse("0W 0N 0W", &.{ .implicit_return, .long_list_literal }, "0W 0N 0W");
    try testParse("0W 0N 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0W");
    try testParse("0W 0N 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0W");
    try testParse("0W 0N -0W", &.{ .implicit_return, .long_list_literal }, "0W 0N -0W");
    try testParse("0W 0N -0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0N -0W");
    try testParse("0W 0N -0wj", &.{ .implicit_return, .long_list_literal }, "0W 0N -0W");
    try testParse("0W 0n 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0N");
    try testParse("0W 0n 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0N");
    try testParse("0W 0n 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0W");
    try testParse("0W 0n 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0W");
    try testParse("0W 0n -0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0N -0W");
    try testParse("0W 0n -0wj", &.{ .implicit_return, .long_list_literal }, "0W 0N -0W");
    try testParse("0W 0W 0N", &.{ .implicit_return, .long_list_literal }, "0W 0W 0N");
    try testParse("0W 0W 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0N");
    try testParse("0W 0W 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0N");
    try testParse("0W 0W 0W", &.{ .implicit_return, .long_list_literal }, "0W 0W 0W");
    try testParse("0W 0W 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0W");
    try testParse("0W 0W 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0W");
    try testParse("0W 0W -0W", &.{ .implicit_return, .long_list_literal }, "0W 0W -0W");
    try testParse("0W 0W -0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W -0W");
    try testParse("0W 0W -0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W -0W");
    try testParse("0W 0w 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0N");
    try testParse("0W 0w 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0N");
    try testParse("0W 0w 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0W");
    try testParse("0W 0w 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0W");
    try testParse("0W 0w -0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W -0W");
    try testParse("0W 0w -0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W -0W");
    try testParse("0W -0W 0N", &.{ .implicit_return, .long_list_literal }, "0W -0W 0N");
    try testParse("0W -0W 0Nj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0N");
    try testParse("0W -0W 0nj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0N");
    try testParse("0W -0W 0W", &.{ .implicit_return, .long_list_literal }, "0W -0W 0W");
    try testParse("0W -0W 0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0W");
    try testParse("0W -0W 0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0W");
    try testParse("0W -0W -0W", &.{ .implicit_return, .long_list_literal }, "0W -0W -0W");
    try testParse("0W -0W -0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W -0W");
    try testParse("0W -0W -0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W -0W");
    try testParse("0W -0w 0Nj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0N");
    try testParse("0W -0w 0nj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0N");
    try testParse("0W -0w 0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0W");
    try testParse("0W -0w 0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0W");
    try testParse("0W -0w -0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W -0W");
    try testParse("0W -0w -0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W -0W");
    try testParse("0w 0N 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0N");
    try testParse("0w 0N 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0N");
    try testParse("0w 0N 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0W");
    try testParse("0w 0N 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0W");
    try testParse("0w 0N -0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0N -0W");
    try testParse("0w 0N -0wj", &.{ .implicit_return, .long_list_literal }, "0W 0N -0W");
    try testParse("0w 0n 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0N");
    try testParse("0w 0n 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0N");
    try testParse("0w 0n 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0W");
    try testParse("0w 0n 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0N 0W");
    try testParse("0w 0n -0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0N -0W");
    try testParse("0w 0n -0wj", &.{ .implicit_return, .long_list_literal }, "0W 0N -0W");
    try testParse("0w 0W 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0N");
    try testParse("0w 0W 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0N");
    try testParse("0w 0W 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0W");
    try testParse("0w 0W 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0W");
    try testParse("0w 0W -0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W -0W");
    try testParse("0w 0W -0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W -0W");
    try testParse("0w 0w 0Nj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0N");
    try testParse("0w 0w 0nj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0N");
    try testParse("0w 0w 0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0W");
    try testParse("0w 0w 0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W 0W");
    try testParse("0w 0w -0Wj", &.{ .implicit_return, .long_list_literal }, "0W 0W -0W");
    try testParse("0w 0w -0wj", &.{ .implicit_return, .long_list_literal }, "0W 0W -0W");
    try testParse("0w -0W 0Nj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0N");
    try testParse("0w -0W 0nj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0N");
    try testParse("0w -0W 0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0W");
    try testParse("0w -0W 0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0W");
    try testParse("0w -0W -0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W -0W");
    try testParse("0w -0W -0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W -0W");
    try testParse("0w -0w 0Nj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0N");
    try testParse("0w -0w 0nj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0N");
    try testParse("0w -0w 0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0W");
    try testParse("0w -0w 0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W 0W");
    try testParse("0w -0w -0Wj", &.{ .implicit_return, .long_list_literal }, "0W -0W -0W");
    try testParse("0w -0w -0wj", &.{ .implicit_return, .long_list_literal }, "0W -0W -0W");
    try testParse("-0W 0N 0N", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0N");
    try testParse("-0W 0N 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0N");
    try testParse("-0W 0N 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0N");
    try testParse("-0W 0N 0W", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0W");
    try testParse("-0W 0N 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0W");
    try testParse("-0W 0N 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0W");
    try testParse("-0W 0N -0W", &.{ .implicit_return, .long_list_literal }, "-0W 0N -0W");
    try testParse("-0W 0N -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N -0W");
    try testParse("-0W 0N -0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N -0W");
    try testParse("-0W 0n 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0N");
    try testParse("-0W 0n 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0N");
    try testParse("-0W 0n 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0W");
    try testParse("-0W 0n 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0W");
    try testParse("-0W 0n -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N -0W");
    try testParse("-0W 0n -0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N -0W");
    try testParse("-0W 0W 0N", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0N");
    try testParse("-0W 0W 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0N");
    try testParse("-0W 0W 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0N");
    try testParse("-0W 0W 0W", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0W");
    try testParse("-0W 0W 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0W");
    try testParse("-0W 0W 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0W");
    try testParse("-0W 0W -0W", &.{ .implicit_return, .long_list_literal }, "-0W 0W -0W");
    try testParse("-0W 0W -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W -0W");
    try testParse("-0W 0W -0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W -0W");
    try testParse("-0W 0w 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0N");
    try testParse("-0W 0w 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0N");
    try testParse("-0W 0w 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0W");
    try testParse("-0W 0w 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0W");
    try testParse("-0W 0w -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W -0W");
    try testParse("-0W 0w -0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W -0W");
    try testParse("-0W -0W 0N", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0N");
    try testParse("-0W -0W 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0N");
    try testParse("-0W -0W 0nj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0N");
    try testParse("-0W -0W 0W", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0W");
    try testParse("-0W -0W 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0W");
    try testParse("-0W -0W 0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0W");
    try testParse("-0W -0W -0W", &.{ .implicit_return, .long_list_literal }, "-0W -0W -0W");
    try testParse("-0W -0W -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W -0W");
    try testParse("-0W -0W -0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W -0W");
    try testParse("-0W -0w 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0N");
    try testParse("-0W -0w 0nj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0N");
    try testParse("-0W -0w 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0W");
    try testParse("-0W -0w 0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0W");
    try testParse("-0W -0w -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W -0W");
    try testParse("-0W -0w -0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W -0W");
    try testParse("-0w 0N 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0N");
    try testParse("-0w 0N 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0N");
    try testParse("-0w 0N 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0W");
    try testParse("-0w 0N 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0W");
    try testParse("-0w 0N -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N -0W");
    try testParse("-0w 0N -0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N -0W");
    try testParse("-0w 0n 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0N");
    try testParse("-0w 0n 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0N");
    try testParse("-0w 0n 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0W");
    try testParse("-0w 0n 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N 0W");
    try testParse("-0w 0n -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N -0W");
    try testParse("-0w 0n -0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0N -0W");
    try testParse("-0w 0W 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0N");
    try testParse("-0w 0W 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0N");
    try testParse("-0w 0W 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0W");
    try testParse("-0w 0W 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0W");
    try testParse("-0w 0W -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W -0W");
    try testParse("-0w 0W -0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W -0W");
    try testParse("-0w 0w 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0N");
    try testParse("-0w 0w 0nj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0N");
    try testParse("-0w 0w 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0W");
    try testParse("-0w 0w 0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W 0W");
    try testParse("-0w 0w -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W -0W");
    try testParse("-0w 0w -0wj", &.{ .implicit_return, .long_list_literal }, "-0W 0W -0W");
    try testParse("-0w -0W 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0N");
    try testParse("-0w -0W 0nj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0N");
    try testParse("-0w -0W 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0W");
    try testParse("-0w -0W 0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0W");
    try testParse("-0w -0W -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W -0W");
    try testParse("-0w -0W -0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W -0W");
    try testParse("-0w -0w 0Nj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0N");
    try testParse("-0w -0w 0nj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0N");
    try testParse("-0w -0w 0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0W");
    try testParse("-0w -0w 0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W 0W");
    try testParse("-0w -0w -0Wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W -0W");
    try testParse("-0w -0w -0wj", &.{ .implicit_return, .long_list_literal }, "-0W -0W -0W");
}

test "invalid long inputs" {
    try testNumberParserError("0jj", error.InvalidCharacter);
    try testNumberParserError("1jj", error.InvalidCharacter);
    try testNumberParserError("-1jj", error.InvalidCharacter);
    try testNumberParserError("9223372036854775806jj", error.InvalidCharacter);
    try testNumberParserError("-9223372036854775806jj", error.InvalidCharacter);
    try testNumberParserError(".1j", error.InvalidCharacter);
    try testNumberParserError("1.j", error.InvalidCharacter);
    try testNumberParserError("1.1j", error.InvalidCharacter);
    try testNumberParserError("9223372036854775808j", error.Overflow);
    try testNumberParserError("-9223372036854775808j", error.Overflow);
    try testNumberParserError("-9223372036854775809j", error.Overflow);

    try testNumberParserError("9223372036854775808", error.Overflow);
    try testNumberParserError("-9223372036854775808", error.Overflow);
    try testNumberParserError("-9223372036854775809", error.Overflow);

    try testParseError("1. 2j", &.{.parse_error});
    try testParseError("1. 2. 3j", &.{.parse_error});

    try testParseError("-9223372036854775808 1", &.{.parse_error});
    try testParseError("-9223372036854775808 1j", &.{.parse_error});
}

test {
    @import("std").testing.refAllDecls(@This());
}
