const number_parser = @import("../number_parser.zig");
const Parse = @import("../../Parse.zig");
const testNumberParser = number_parser.testNumberParser;
const testNumberParserError = number_parser.testNumberParserError;
const testParse = Parse.testParse;
const testParseError = Parse.testParseError;
const null_int = number_parser.null_int;
const inf_int = number_parser.inf_int;

test "valid minute inputs" {
    try testNumberParser("0nu", .minute, null_int);
    try testNumberParser("0Nu", .minute, null_int);
    try testNumberParser("0wu", .minute, inf_int);
    try testNumberParser("0Wu", .minute, inf_int);
    try testNumberParser("-0wu", .minute, -inf_int);
    try testNumberParser("-0Wu", .minute, -inf_int);

    try testNumberParser("0u", .minute, 0);
    try testNumberParser("9u", .minute, 540);
    try testNumberParser("-9u", .minute, -540);

    try testNumberParser("00u", .minute, 0);
    try testNumberParser("99u", .minute, 5940);
    try testNumberParser("-99u", .minute, -5940);

    try testNumberParser("000u", .minute, 0);
    try testNumberParser("959u", .minute, 599);
    try testNumberParser("-959u", .minute, -599);

    try testNumberParser("0000u", .minute, 0);
    try testNumberParser("9959u", .minute, 5999);
    try testNumberParser("-9959u", .minute, -5999);

    try testNumberParser("00000u", .minute, 0);
    try testNumberParser("99959u", .minute, 59999);
    try testNumberParser("-99959u", .minute, -59999);

    try testNumberParser("000000u", .minute, 0);
    try testNumberParser("999959u", .minute, 599999);
    try testNumberParser("-999959u", .minute, -599999);

    try testNumberParser("0000000u", .minute, 0);
    try testNumberParser("9999959u", .minute, 5999999);
    try testNumberParser("-9999959u", .minute, -5999999);

    try testNumberParser("00000000u", .minute, 0);
    try testNumberParser("99999959u", .minute, 59999999);
    try testNumberParser("-99999959u", .minute, -59999999);

    try testNumberParser("000000000u", .minute, 0);
    try testNumberParser("999999959u", .minute, 599999999);
    try testNumberParser("-999999959u", .minute, -599999999);

    try testNumberParser("0000000000u", .minute, 0);
    try testNumberParser("9999999959u", .minute, 1705032703);
    try testNumberParser("-9999999959u", .minute, -1705032703);

    try testNumberParser("00000000000u", .minute, 0);
    try testNumberParser("99999999959u", .minute, -129542145);
    try testNumberParser("-99999999959u", .minute, 129542145);

    try testNumberParser("000000000000u", .minute, 0);
    try testNumberParser("214748364759u", .minute, -1);
    try testNumberParser("-214748364759u", .minute, 1);

    try testNumberParser("00:00", .minute, 0);
    try testNumberParser("99:59", .minute, 5999);
    try testNumberParser("-99:59", .minute, -5999);

    try testNumberParser("000:00", .minute, 0);
    try testNumberParser("999:59", .minute, 59999);

    try testParse("00:00", &.{ .implicit_return, .minute_literal }, "00:00");

    try testParse("0 9 -9u", &.{ .implicit_return, .minute_list_literal }, "00:00 09:00 -09:00");
    try testParse("00 99 -99u", &.{ .implicit_return, .minute_list_literal }, "00:00 99:00 -99:00");
    try testParse("000 959 -959u", &.{ .implicit_return, .minute_list_literal }, "00:00 09:59 -09:59");
    try testParse("0000 9959 -9959u", &.{ .implicit_return, .minute_list_literal }, "00:00 99:59 -99:59");
    try testParse("00000 99959 -99959u", &.{ .implicit_return, .minute_list_literal }, "00:00 **:59 -**:59");
    try testParse("000000000000 214748364759 -214748364759u", &.{ .implicit_return, .minute_list_literal }, "00:00 -00:01 00:01");
    try testParse("00:00 99:59 -99:59 000:00 999:59", &.{ .implicit_return, .minute_list_literal }, "00:00 99:59 -99:59 00:00 **:59");

    try testParse("0Nu", &.{ .implicit_return, .minute_literal }, "0Nu");
    try testParse("0nu", &.{ .implicit_return, .minute_literal }, "0Nu");
    try testParse("0Wu", &.{ .implicit_return, .minute_literal }, "0Wu");
    try testParse("0wu", &.{ .implicit_return, .minute_literal }, "0Wu");
    try testParse("-0Wu", &.{ .implicit_return, .minute_literal }, "-0Wu");
    try testParse("-0wu", &.{ .implicit_return, .minute_literal }, "-0Wu");

    try testParse("0N 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0Nu");
    try testParse("0N 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0Nu");
    try testParse("0N 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0Wu");
    try testParse("0N 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0Wu");
    try testParse("0N -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0Wu");
    try testParse("0N -0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0Wu");
    try testParse("0n 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0Nu");
    try testParse("0n 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0Nu");
    try testParse("0n 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0Wu");
    try testParse("0n 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0Wu");
    try testParse("0n -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0Wu");
    try testParse("0n -0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0Wu");
    try testParse("0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0Nu");
    try testParse("0W 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0Nu");
    try testParse("0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0Wu");
    try testParse("0W 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0Wu");
    try testParse("0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0Wu");
    try testParse("0W -0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0Wu");
    try testParse("0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0Nu");
    try testParse("0w 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0Nu");
    try testParse("0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0Wu");
    try testParse("0w 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0Wu");
    try testParse("0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0Wu");
    try testParse("0w -0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0Wu");
    try testParse("-0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0Nu");
    try testParse("-0W 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0Nu");
    try testParse("-0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0Wu");
    try testParse("-0W 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0Wu");
    try testParse("-0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0Wu");
    try testParse("-0W -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0Wu");
    try testParse("-0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0Nu");
    try testParse("-0w 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0Nu");
    try testParse("-0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0Wu");
    try testParse("-0w 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0Wu");
    try testParse("-0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0Wu");
    try testParse("-0w -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0Wu");

    try testParse("0N 0N 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Nu");
    try testParse("0N 0N 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Nu");
    try testParse("0N 0N 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Wu");
    try testParse("0N 0N 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Wu");
    try testParse("0N 0N -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N -0Wu");
    try testParse("0N 0N -0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N -0Wu");
    try testParse("0N 0n 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Nu");
    try testParse("0N 0n 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Nu");
    try testParse("0N 0n 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Wu");
    try testParse("0N 0n 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Wu");
    try testParse("0N 0n -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N -0Wu");
    try testParse("0N 0n -0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N -0Wu");
    try testParse("0N 0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Nu");
    try testParse("0N 0W 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Nu");
    try testParse("0N 0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Wu");
    try testParse("0N 0W 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Wu");
    try testParse("0N 0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W -0Wu");
    try testParse("0N 0W -0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W -0Wu");
    try testParse("0N 0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Nu");
    try testParse("0N 0w 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Nu");
    try testParse("0N 0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Wu");
    try testParse("0N 0w 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Wu");
    try testParse("0N 0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W -0Wu");
    try testParse("0N 0w -0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W -0Wu");
    try testParse("0N -0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Nu");
    try testParse("0N -0W 0nu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Nu");
    try testParse("0N -0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Wu");
    try testParse("0N -0W 0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Wu");
    try testParse("0N -0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W -0Wu");
    try testParse("0N -0W -0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W -0Wu");
    try testParse("0N -0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Nu");
    try testParse("0N -0w 0nu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Nu");
    try testParse("0N -0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Wu");
    try testParse("0N -0w 0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Wu");
    try testParse("0N -0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W -0Wu");
    try testParse("0N -0w -0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W -0Wu");
    try testParse("0n 0N 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Nu");
    try testParse("0n 0N 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Nu");
    try testParse("0n 0N 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Wu");
    try testParse("0n 0N 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Wu");
    try testParse("0n 0N -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N -0Wu");
    try testParse("0n 0N -0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N -0Wu");
    try testParse("0n 0n 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Nu");
    try testParse("0n 0n 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Nu");
    try testParse("0n 0n 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Wu");
    try testParse("0n 0n 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N 0Wu");
    try testParse("0n 0n -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N -0Wu");
    try testParse("0n 0n -0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0N -0Wu");
    try testParse("0n 0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Nu");
    try testParse("0n 0W 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Nu");
    try testParse("0n 0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Wu");
    try testParse("0n 0W 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Wu");
    try testParse("0n 0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W -0Wu");
    try testParse("0n 0W -0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W -0Wu");
    try testParse("0n 0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Nu");
    try testParse("0n 0w 0nu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Nu");
    try testParse("0n 0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Wu");
    try testParse("0n 0w 0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W 0Wu");
    try testParse("0n 0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W -0Wu");
    try testParse("0n 0w -0wu", &.{ .implicit_return, .minute_list_literal }, "0N 0W -0Wu");
    try testParse("0n -0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Nu");
    try testParse("0n -0W 0nu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Nu");
    try testParse("0n -0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Wu");
    try testParse("0n -0W 0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Wu");
    try testParse("0n -0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W -0Wu");
    try testParse("0n -0W -0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W -0Wu");
    try testParse("0n -0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Nu");
    try testParse("0n -0w 0nu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Nu");
    try testParse("0n -0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Wu");
    try testParse("0n -0w 0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W 0Wu");
    try testParse("0n -0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W -0Wu");
    try testParse("0n -0w -0wu", &.{ .implicit_return, .minute_list_literal }, "0N -0W -0Wu");
    try testParse("0W 0N 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Nu");
    try testParse("0W 0N 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Nu");
    try testParse("0W 0N 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Wu");
    try testParse("0W 0N 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Wu");
    try testParse("0W 0N -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N -0Wu");
    try testParse("0W 0N -0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N -0Wu");
    try testParse("0W 0n 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Nu");
    try testParse("0W 0n 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Nu");
    try testParse("0W 0n 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Wu");
    try testParse("0W 0n 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Wu");
    try testParse("0W 0n -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N -0Wu");
    try testParse("0W 0n -0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N -0Wu");
    try testParse("0W 0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Nu");
    try testParse("0W 0W 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Nu");
    try testParse("0W 0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Wu");
    try testParse("0W 0W 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Wu");
    try testParse("0W 0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W -0Wu");
    try testParse("0W 0W -0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W -0Wu");
    try testParse("0W 0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Nu");
    try testParse("0W 0w 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Nu");
    try testParse("0W 0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Wu");
    try testParse("0W 0w 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Wu");
    try testParse("0W 0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W -0Wu");
    try testParse("0W 0w -0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W -0Wu");
    try testParse("0W -0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Nu");
    try testParse("0W -0W 0nu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Nu");
    try testParse("0W -0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Wu");
    try testParse("0W -0W 0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Wu");
    try testParse("0W -0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W -0Wu");
    try testParse("0W -0W -0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W -0Wu");
    try testParse("0W -0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Nu");
    try testParse("0W -0w 0nu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Nu");
    try testParse("0W -0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Wu");
    try testParse("0W -0w 0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Wu");
    try testParse("0W -0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W -0Wu");
    try testParse("0W -0w -0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W -0Wu");
    try testParse("0w 0N 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Nu");
    try testParse("0w 0N 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Nu");
    try testParse("0w 0N 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Wu");
    try testParse("0w 0N 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Wu");
    try testParse("0w 0N -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N -0Wu");
    try testParse("0w 0N -0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N -0Wu");
    try testParse("0w 0n 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Nu");
    try testParse("0w 0n 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Nu");
    try testParse("0w 0n 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Wu");
    try testParse("0w 0n 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N 0Wu");
    try testParse("0w 0n -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N -0Wu");
    try testParse("0w 0n -0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0N -0Wu");
    try testParse("0w 0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Nu");
    try testParse("0w 0W 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Nu");
    try testParse("0w 0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Wu");
    try testParse("0w 0W 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Wu");
    try testParse("0w 0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W -0Wu");
    try testParse("0w 0W -0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W -0Wu");
    try testParse("0w 0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Nu");
    try testParse("0w 0w 0nu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Nu");
    try testParse("0w 0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Wu");
    try testParse("0w 0w 0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W 0Wu");
    try testParse("0w 0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W -0Wu");
    try testParse("0w 0w -0wu", &.{ .implicit_return, .minute_list_literal }, "0W 0W -0Wu");
    try testParse("0w -0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Nu");
    try testParse("0w -0W 0nu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Nu");
    try testParse("0w -0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Wu");
    try testParse("0w -0W 0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Wu");
    try testParse("0w -0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W -0Wu");
    try testParse("0w -0W -0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W -0Wu");
    try testParse("0w -0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Nu");
    try testParse("0w -0w 0nu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Nu");
    try testParse("0w -0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Wu");
    try testParse("0w -0w 0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W 0Wu");
    try testParse("0w -0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W -0Wu");
    try testParse("0w -0w -0wu", &.{ .implicit_return, .minute_list_literal }, "0W -0W -0Wu");
    try testParse("-0W 0N 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Nu");
    try testParse("-0W 0N 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Nu");
    try testParse("-0W 0N 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Wu");
    try testParse("-0W 0N 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Wu");
    try testParse("-0W 0N -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N -0Wu");
    try testParse("-0W 0N -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N -0Wu");
    try testParse("-0W 0n 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Nu");
    try testParse("-0W 0n 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Nu");
    try testParse("-0W 0n 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Wu");
    try testParse("-0W 0n 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Wu");
    try testParse("-0W 0n -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N -0Wu");
    try testParse("-0W 0n -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N -0Wu");
    try testParse("-0W 0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Nu");
    try testParse("-0W 0W 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Nu");
    try testParse("-0W 0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Wu");
    try testParse("-0W 0W 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Wu");
    try testParse("-0W 0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W -0Wu");
    try testParse("-0W 0W -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W -0Wu");
    try testParse("-0W 0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Nu");
    try testParse("-0W 0w 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Nu");
    try testParse("-0W 0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Wu");
    try testParse("-0W 0w 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Wu");
    try testParse("-0W 0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W -0Wu");
    try testParse("-0W 0w -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W -0Wu");
    try testParse("-0W -0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Nu");
    try testParse("-0W -0W 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Nu");
    try testParse("-0W -0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Wu");
    try testParse("-0W -0W 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Wu");
    try testParse("-0W -0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W -0Wu");
    try testParse("-0W -0W -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W -0Wu");
    try testParse("-0W -0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Nu");
    try testParse("-0W -0w 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Nu");
    try testParse("-0W -0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Wu");
    try testParse("-0W -0w 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Wu");
    try testParse("-0W -0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W -0Wu");
    try testParse("-0W -0w -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W -0Wu");
    try testParse("-0w 0N 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Nu");
    try testParse("-0w 0N 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Nu");
    try testParse("-0w 0N 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Wu");
    try testParse("-0w 0N 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Wu");
    try testParse("-0w 0N -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N -0Wu");
    try testParse("-0w 0N -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N -0Wu");
    try testParse("-0w 0n 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Nu");
    try testParse("-0w 0n 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Nu");
    try testParse("-0w 0n 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Wu");
    try testParse("-0w 0n 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N 0Wu");
    try testParse("-0w 0n -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N -0Wu");
    try testParse("-0w 0n -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0N -0Wu");
    try testParse("-0w 0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Nu");
    try testParse("-0w 0W 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Nu");
    try testParse("-0w 0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Wu");
    try testParse("-0w 0W 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Wu");
    try testParse("-0w 0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W -0Wu");
    try testParse("-0w 0W -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W -0Wu");
    try testParse("-0w 0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Nu");
    try testParse("-0w 0w 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Nu");
    try testParse("-0w 0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Wu");
    try testParse("-0w 0w 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W 0Wu");
    try testParse("-0w 0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W -0Wu");
    try testParse("-0w 0w -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W 0W -0Wu");
    try testParse("-0w -0W 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Nu");
    try testParse("-0w -0W 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Nu");
    try testParse("-0w -0W 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Wu");
    try testParse("-0w -0W 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Wu");
    try testParse("-0w -0W -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W -0Wu");
    try testParse("-0w -0W -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W -0Wu");
    try testParse("-0w -0w 0Nu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Nu");
    try testParse("-0w -0w 0nu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Nu");
    try testParse("-0w -0w 0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Wu");
    try testParse("-0w -0w 0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W 0Wu");
    try testParse("-0w -0w -0Wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W -0Wu");
    try testParse("-0w -0w -0wu", &.{ .implicit_return, .minute_list_literal }, "-0W -0W -0Wu");
}

test "invalid minute inputs" {
    try testNumberParserError("-9:", error.InvalidCharacter);
    try testNumberParserError("-9:0", error.InvalidCharacter);
    try testNumberParserError("-9:00", error.InvalidCharacter);
    try testNumberParserError("-99:", error.InvalidCharacter);
    try testNumberParserError("00:", error.InvalidCharacter);
    try testNumberParserError("00:0", error.InvalidCharacter);
    try testNumberParserError("-99:", error.InvalidCharacter);
    try testNumberParserError("-99:0", error.InvalidCharacter);
    try testNumberParserError("00:60", error.Overflow);
    try testNumberParserError("000:", error.InvalidCharacter);
    try testNumberParserError("000:0", error.InvalidCharacter);
    try testNumberParserError("000:60", error.Overflow);
    try testNumberParserError("-999:", error.InvalidCharacter);
    try testNumberParserError("-999:0", error.InvalidCharacter);
    try testNumberParserError("-999:00", error.InvalidCharacter);

    try testNumberParserError("060u", error.Overflow);
    try testNumberParserError("960u", error.Overflow);
    try testNumberParserError("-960u", error.Overflow);

    try testNumberParserError("0060u", error.Overflow);
    try testNumberParserError("9960u", error.Overflow);
    try testNumberParserError("-9960u", error.Overflow);

    try testNumberParserError("000000000060u", error.Overflow);
    try testNumberParserError("214748364859u", error.Overflow);
    try testNumberParserError("214748364760u", error.Overflow);
    try testNumberParserError("-214748364859u", error.Overflow);
    try testNumberParserError("-214748364760u", error.Overflow);

    try testParseError("-9:00", &.{.parse_error});
    try testParseError("00:60", &.{.parse_error});
    try testParseError("000:60", &.{.parse_error});
    try testParseError("-999:00", &.{.parse_error});

    try testParseError("00:00 10:00 -20:00 00:60", &.{.parse_error});
    try testParseError("00:00 10:00 -20:00 000:60", &.{.parse_error});
    try testParseError("00:00 10:00 -20:00 -999:00", &.{.parse_error});

    try testParseError("00:00 10:00 -20:00 000000000060u", &.{.parse_error});
}

test {
    @import("std").testing.refAllDecls(@This());
}
