const number_parser = @import("../number_parser.zig");
const Parse = @import("../../Parse.zig");
const testNumberParser = number_parser.testNumberParser;
const testNumberParserError = number_parser.testNumberParserError;
const testParse = Parse.testParse;
const testParseError = Parse.testParseError;
const null_int = number_parser.null_int;
const inf_int = number_parser.inf_int;

test "valid month inputs" {
    const _std = @import("std");
    const _clock: _std.Io.Clock = .real;
    const _start = try _clock.now(_std.testing.io);
    const _file: _std.fs.File = .adaptFromNewApi(try _std.Io.Dir.cwd().createFile(_std.testing.io, @src().fn_name ++ ".log", .{}));
    defer _file.close();
    var _file_writer = _file.writer(&.{});
    const _writer = &_file_writer.interface;
    try _writer.writeAll(@src().fn_name);
    try _writer.flush();
    defer {
        _writer.print(": {d}ms\n", .{_start.durationTo(_clock.now(_std.testing.io) catch unreachable).toMilliseconds()}) catch unreachable;
        _writer.flush() catch unreachable;
    }
    try testNumberParser("1999.12m", .month, -1);
    try testNumberParser("2000.01m", .month, 0);
    try testNumberParser("2000.02m", .month, 1);
    try testNumberParser("-1999.12m", .month, 1);
    try testNumberParser("0001.01m", .month, -23988);
    try testNumberParser("9999.12m", .month, 95999);
    try testNumberParser("0Nm", .month, null_int);
    try testNumberParser("0nm", .month, null_int);
    try testNumberParser("0Wm", .month, inf_int);
    try testNumberParser("0wm", .month, inf_int);
    try testNumberParser("-0Wm", .month, -inf_int);
    try testNumberParser("-0wm", .month, -inf_int);

    try testNumberParser("0001m", .month, 0);
    try testNumberParser("0012m", .month, 11);
    try testNumberParser("4912m", .month, 599);
    try testNumberParser("5001m", .month, -600);
    try testNumberParser("9901m", .month, -12);
    try testNumberParser("9912m", .month, -1);

    try testNumberParser("000101m", .month, -23988);
    try testNumberParser("000112m", .month, -23977);
    try testNumberParser("999901m", .month, 95988);
    try testNumberParser("999912m", .month, 95999);

    try testParse("2000.01m", &.{ .implicit_return, .month_literal }, "2000.01m");
    try testParse("1999.12m", &.{ .implicit_return, .month_literal }, "1999.12m");
    try testParse("5001m", &.{ .implicit_return, .month_literal }, "1950.01m");

    try testParse("2000.01 2001.02m", &.{ .implicit_return, .month_list_literal }, "2000.01 2001.02m");
    try testParse("2000.01 4912m", &.{ .implicit_return, .month_list_literal }, "2000.01 2049.12m");
    try testParse("4912 2001.02m", &.{ .implicit_return, .month_list_literal }, "2049.12 2001.02m");
    try testParse("4912 4912m", &.{ .implicit_return, .month_list_literal }, "2049.12 2049.12m");

    try testParse("2000.01 2001.02 2002.03m", &.{ .implicit_return, .month_list_literal }, "2000.01 2001.02 2002.03m");
    try testParse("2000.01 2001.02 4912m", &.{ .implicit_return, .month_list_literal }, "2000.01 2001.02 2049.12m");
    try testParse("2000.01 4912 2002.03m", &.{ .implicit_return, .month_list_literal }, "2000.01 2049.12 2002.03m");
    try testParse("2000.01 4912 4912m", &.{ .implicit_return, .month_list_literal }, "2000.01 2049.12 2049.12m");
    try testParse("4912 2001.02 2002.03m", &.{ .implicit_return, .month_list_literal }, "2049.12 2001.02 2002.03m");
    try testParse("4912 2001.02 4912m", &.{ .implicit_return, .month_list_literal }, "2049.12 2001.02 2049.12m");
    try testParse("4912 4912 2002.03m", &.{ .implicit_return, .month_list_literal }, "2049.12 2049.12 2002.03m");
    try testParse("4912 4912 4912m", &.{ .implicit_return, .month_list_literal }, "2049.12 2049.12 2049.12m");

    try testParse("2000.01 2010.03 2020.06 2030.09 2040.12m", &.{ .implicit_return, .month_list_literal }, "2000.01 2010.03 2020.06 2030.09 2040.12m");
    try testParse("0001 0012 4912 5001 9901 9912m", &.{ .implicit_return, .month_list_literal }, "2000.01 2000.12 2049.12 1950.01 1999.01 1999.12m");
    try testParse("000101 000112 999901 999912m", &.{ .implicit_return, .month_list_literal }, "0001.01 0001.12 9999.01 9999.12m");

    try testParse("0Nm", &.{ .implicit_return, .month_literal }, "0Nm");
    try testParse("0nm", &.{ .implicit_return, .month_literal }, "0Nm");
    try testParse("0Wm", &.{ .implicit_return, .month_literal }, "0Wm");
    try testParse("0wm", &.{ .implicit_return, .month_literal }, "0Wm");
    try testParse("-0Wm", &.{ .implicit_return, .month_literal }, "-0Wm");
    try testParse("-0wm", &.{ .implicit_return, .month_literal }, "-0Wm");

    try testParse("0N 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0Nm");
    try testParse("0N 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0Nm");
    try testParse("0N 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0Wm");
    try testParse("0N 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0Wm");
    try testParse("0N -0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0Wm");
    try testParse("0N -0wm", &.{ .implicit_return, .month_list_literal }, "0N -0Wm");
    try testParse("0n 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0Nm");
    try testParse("0n 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0Nm");
    try testParse("0n 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0Wm");
    try testParse("0n 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0Wm");
    try testParse("0n -0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0Wm");
    try testParse("0n -0wm", &.{ .implicit_return, .month_list_literal }, "0N -0Wm");
    try testParse("0W 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0Nm");
    try testParse("0W 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0Nm");
    try testParse("0W 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0Wm");
    try testParse("0W 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0Wm");
    try testParse("0W -0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0Wm");
    try testParse("0W -0wm", &.{ .implicit_return, .month_list_literal }, "0W -0Wm");
    try testParse("0w 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0Nm");
    try testParse("0w 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0Nm");
    try testParse("0w 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0Wm");
    try testParse("0w 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0Wm");
    try testParse("0w -0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0Wm");
    try testParse("0w -0wm", &.{ .implicit_return, .month_list_literal }, "0W -0Wm");
    try testParse("-0W 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0Nm");
    try testParse("-0W 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0Nm");
    try testParse("-0W 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0Wm");
    try testParse("-0W 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0Wm");
    try testParse("-0W -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0Wm");
    try testParse("-0W -0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0Wm");
    try testParse("-0w 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0Nm");
    try testParse("-0w 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0Nm");
    try testParse("-0w 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0Wm");
    try testParse("-0w 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0Wm");
    try testParse("-0w -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0Wm");
    try testParse("-0w -0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0Wm");

    try testParse("0N 0N 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Nm");
    try testParse("0N 0N 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Nm");
    try testParse("0N 0N 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Wm");
    try testParse("0N 0N 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Wm");
    try testParse("0N 0N -0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0N -0Wm");
    try testParse("0N 0N -0wm", &.{ .implicit_return, .month_list_literal }, "0N 0N -0Wm");
    try testParse("0N 0n 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Nm");
    try testParse("0N 0n 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Nm");
    try testParse("0N 0n 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Wm");
    try testParse("0N 0n 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Wm");
    try testParse("0N 0n -0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0N -0Wm");
    try testParse("0N 0n -0wm", &.{ .implicit_return, .month_list_literal }, "0N 0N -0Wm");
    try testParse("0N 0W 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Nm");
    try testParse("0N 0W 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Nm");
    try testParse("0N 0W 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Wm");
    try testParse("0N 0W 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Wm");
    try testParse("0N 0W -0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0W -0Wm");
    try testParse("0N 0W -0wm", &.{ .implicit_return, .month_list_literal }, "0N 0W -0Wm");
    try testParse("0N 0w 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Nm");
    try testParse("0N 0w 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Nm");
    try testParse("0N 0w 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Wm");
    try testParse("0N 0w 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Wm");
    try testParse("0N 0w -0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0W -0Wm");
    try testParse("0N 0w -0wm", &.{ .implicit_return, .month_list_literal }, "0N 0W -0Wm");
    try testParse("0N -0W 0Nm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Nm");
    try testParse("0N -0W 0nm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Nm");
    try testParse("0N -0W 0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Wm");
    try testParse("0N -0W 0wm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Wm");
    try testParse("0N -0W -0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0W -0Wm");
    try testParse("0N -0W -0wm", &.{ .implicit_return, .month_list_literal }, "0N -0W -0Wm");
    try testParse("0N -0w 0Nm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Nm");
    try testParse("0N -0w 0nm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Nm");
    try testParse("0N -0w 0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Wm");
    try testParse("0N -0w 0wm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Wm");
    try testParse("0N -0w -0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0W -0Wm");
    try testParse("0N -0w -0wm", &.{ .implicit_return, .month_list_literal }, "0N -0W -0Wm");
    try testParse("0n 0N 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Nm");
    try testParse("0n 0N 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Nm");
    try testParse("0n 0N 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Wm");
    try testParse("0n 0N 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Wm");
    try testParse("0n 0N -0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0N -0Wm");
    try testParse("0n 0N -0wm", &.{ .implicit_return, .month_list_literal }, "0N 0N -0Wm");
    try testParse("0n 0n 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Nm");
    try testParse("0n 0n 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Nm");
    try testParse("0n 0n 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Wm");
    try testParse("0n 0n 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0N 0Wm");
    try testParse("0n 0n -0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0N -0Wm");
    try testParse("0n 0n -0wm", &.{ .implicit_return, .month_list_literal }, "0N 0N -0Wm");
    try testParse("0n 0W 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Nm");
    try testParse("0n 0W 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Nm");
    try testParse("0n 0W 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Wm");
    try testParse("0n 0W 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Wm");
    try testParse("0n 0W -0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0W -0Wm");
    try testParse("0n 0W -0wm", &.{ .implicit_return, .month_list_literal }, "0N 0W -0Wm");
    try testParse("0n 0w 0Nm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Nm");
    try testParse("0n 0w 0nm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Nm");
    try testParse("0n 0w 0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Wm");
    try testParse("0n 0w 0wm", &.{ .implicit_return, .month_list_literal }, "0N 0W 0Wm");
    try testParse("0n 0w -0Wm", &.{ .implicit_return, .month_list_literal }, "0N 0W -0Wm");
    try testParse("0n 0w -0wm", &.{ .implicit_return, .month_list_literal }, "0N 0W -0Wm");
    try testParse("0n -0W 0Nm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Nm");
    try testParse("0n -0W 0nm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Nm");
    try testParse("0n -0W 0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Wm");
    try testParse("0n -0W 0wm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Wm");
    try testParse("0n -0W -0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0W -0Wm");
    try testParse("0n -0W -0wm", &.{ .implicit_return, .month_list_literal }, "0N -0W -0Wm");
    try testParse("0n -0w 0Nm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Nm");
    try testParse("0n -0w 0nm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Nm");
    try testParse("0n -0w 0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Wm");
    try testParse("0n -0w 0wm", &.{ .implicit_return, .month_list_literal }, "0N -0W 0Wm");
    try testParse("0n -0w -0Wm", &.{ .implicit_return, .month_list_literal }, "0N -0W -0Wm");
    try testParse("0n -0w -0wm", &.{ .implicit_return, .month_list_literal }, "0N -0W -0Wm");
    try testParse("0W 0N 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Nm");
    try testParse("0W 0N 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Nm");
    try testParse("0W 0N 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Wm");
    try testParse("0W 0N 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Wm");
    try testParse("0W 0N -0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0N -0Wm");
    try testParse("0W 0N -0wm", &.{ .implicit_return, .month_list_literal }, "0W 0N -0Wm");
    try testParse("0W 0n 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Nm");
    try testParse("0W 0n 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Nm");
    try testParse("0W 0n 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Wm");
    try testParse("0W 0n 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Wm");
    try testParse("0W 0n -0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0N -0Wm");
    try testParse("0W 0n -0wm", &.{ .implicit_return, .month_list_literal }, "0W 0N -0Wm");
    try testParse("0W 0W 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Nm");
    try testParse("0W 0W 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Nm");
    try testParse("0W 0W 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Wm");
    try testParse("0W 0W 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Wm");
    try testParse("0W 0W -0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0W -0Wm");
    try testParse("0W 0W -0wm", &.{ .implicit_return, .month_list_literal }, "0W 0W -0Wm");
    try testParse("0W 0w 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Nm");
    try testParse("0W 0w 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Nm");
    try testParse("0W 0w 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Wm");
    try testParse("0W 0w 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Wm");
    try testParse("0W 0w -0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0W -0Wm");
    try testParse("0W 0w -0wm", &.{ .implicit_return, .month_list_literal }, "0W 0W -0Wm");
    try testParse("0W -0W 0Nm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Nm");
    try testParse("0W -0W 0nm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Nm");
    try testParse("0W -0W 0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Wm");
    try testParse("0W -0W 0wm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Wm");
    try testParse("0W -0W -0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0W -0Wm");
    try testParse("0W -0W -0wm", &.{ .implicit_return, .month_list_literal }, "0W -0W -0Wm");
    try testParse("0W -0w 0Nm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Nm");
    try testParse("0W -0w 0nm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Nm");
    try testParse("0W -0w 0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Wm");
    try testParse("0W -0w 0wm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Wm");
    try testParse("0W -0w -0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0W -0Wm");
    try testParse("0W -0w -0wm", &.{ .implicit_return, .month_list_literal }, "0W -0W -0Wm");
    try testParse("0w 0N 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Nm");
    try testParse("0w 0N 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Nm");
    try testParse("0w 0N 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Wm");
    try testParse("0w 0N 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Wm");
    try testParse("0w 0N -0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0N -0Wm");
    try testParse("0w 0N -0wm", &.{ .implicit_return, .month_list_literal }, "0W 0N -0Wm");
    try testParse("0w 0n 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Nm");
    try testParse("0w 0n 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Nm");
    try testParse("0w 0n 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Wm");
    try testParse("0w 0n 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0N 0Wm");
    try testParse("0w 0n -0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0N -0Wm");
    try testParse("0w 0n -0wm", &.{ .implicit_return, .month_list_literal }, "0W 0N -0Wm");
    try testParse("0w 0W 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Nm");
    try testParse("0w 0W 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Nm");
    try testParse("0w 0W 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Wm");
    try testParse("0w 0W 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Wm");
    try testParse("0w 0W -0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0W -0Wm");
    try testParse("0w 0W -0wm", &.{ .implicit_return, .month_list_literal }, "0W 0W -0Wm");
    try testParse("0w 0w 0Nm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Nm");
    try testParse("0w 0w 0nm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Nm");
    try testParse("0w 0w 0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Wm");
    try testParse("0w 0w 0wm", &.{ .implicit_return, .month_list_literal }, "0W 0W 0Wm");
    try testParse("0w 0w -0Wm", &.{ .implicit_return, .month_list_literal }, "0W 0W -0Wm");
    try testParse("0w 0w -0wm", &.{ .implicit_return, .month_list_literal }, "0W 0W -0Wm");
    try testParse("0w -0W 0Nm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Nm");
    try testParse("0w -0W 0nm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Nm");
    try testParse("0w -0W 0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Wm");
    try testParse("0w -0W 0wm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Wm");
    try testParse("0w -0W -0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0W -0Wm");
    try testParse("0w -0W -0wm", &.{ .implicit_return, .month_list_literal }, "0W -0W -0Wm");
    try testParse("0w -0w 0Nm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Nm");
    try testParse("0w -0w 0nm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Nm");
    try testParse("0w -0w 0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Wm");
    try testParse("0w -0w 0wm", &.{ .implicit_return, .month_list_literal }, "0W -0W 0Wm");
    try testParse("0w -0w -0Wm", &.{ .implicit_return, .month_list_literal }, "0W -0W -0Wm");
    try testParse("0w -0w -0wm", &.{ .implicit_return, .month_list_literal }, "0W -0W -0Wm");
    try testParse("-0W 0N 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Nm");
    try testParse("-0W 0N 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Nm");
    try testParse("-0W 0N 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Wm");
    try testParse("-0W 0N 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Wm");
    try testParse("-0W 0N -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N -0Wm");
    try testParse("-0W 0N -0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N -0Wm");
    try testParse("-0W 0n 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Nm");
    try testParse("-0W 0n 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Nm");
    try testParse("-0W 0n 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Wm");
    try testParse("-0W 0n 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Wm");
    try testParse("-0W 0n -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N -0Wm");
    try testParse("-0W 0n -0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N -0Wm");
    try testParse("-0W 0W 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Nm");
    try testParse("-0W 0W 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Nm");
    try testParse("-0W 0W 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Wm");
    try testParse("-0W 0W 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Wm");
    try testParse("-0W 0W -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W -0Wm");
    try testParse("-0W 0W -0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W -0Wm");
    try testParse("-0W 0w 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Nm");
    try testParse("-0W 0w 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Nm");
    try testParse("-0W 0w 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Wm");
    try testParse("-0W 0w 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Wm");
    try testParse("-0W 0w -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W -0Wm");
    try testParse("-0W 0w -0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W -0Wm");
    try testParse("-0W -0W 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Nm");
    try testParse("-0W -0W 0nm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Nm");
    try testParse("-0W -0W 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Wm");
    try testParse("-0W -0W 0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Wm");
    try testParse("-0W -0W -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W -0Wm");
    try testParse("-0W -0W -0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W -0Wm");
    try testParse("-0W -0w 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Nm");
    try testParse("-0W -0w 0nm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Nm");
    try testParse("-0W -0w 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Wm");
    try testParse("-0W -0w 0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Wm");
    try testParse("-0W -0w -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W -0Wm");
    try testParse("-0W -0w -0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W -0Wm");
    try testParse("-0w 0N 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Nm");
    try testParse("-0w 0N 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Nm");
    try testParse("-0w 0N 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Wm");
    try testParse("-0w 0N 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Wm");
    try testParse("-0w 0N -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N -0Wm");
    try testParse("-0w 0N -0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N -0Wm");
    try testParse("-0w 0n 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Nm");
    try testParse("-0w 0n 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Nm");
    try testParse("-0w 0n 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Wm");
    try testParse("-0w 0n 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N 0Wm");
    try testParse("-0w 0n -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N -0Wm");
    try testParse("-0w 0n -0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0N -0Wm");
    try testParse("-0w 0W 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Nm");
    try testParse("-0w 0W 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Nm");
    try testParse("-0w 0W 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Wm");
    try testParse("-0w 0W 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Wm");
    try testParse("-0w 0W -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W -0Wm");
    try testParse("-0w 0W -0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W -0Wm");
    try testParse("-0w 0w 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Nm");
    try testParse("-0w 0w 0nm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Nm");
    try testParse("-0w 0w 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Wm");
    try testParse("-0w 0w 0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W 0Wm");
    try testParse("-0w 0w -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W -0Wm");
    try testParse("-0w 0w -0wm", &.{ .implicit_return, .month_list_literal }, "-0W 0W -0Wm");
    try testParse("-0w -0W 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Nm");
    try testParse("-0w -0W 0nm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Nm");
    try testParse("-0w -0W 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Wm");
    try testParse("-0w -0W 0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Wm");
    try testParse("-0w -0W -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W -0Wm");
    try testParse("-0w -0W -0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W -0Wm");
    try testParse("-0w -0w 0Nm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Nm");
    try testParse("-0w -0w 0nm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Nm");
    try testParse("-0w -0w 0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Wm");
    try testParse("-0w -0w 0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W 0Wm");
    try testParse("-0w -0w -0Wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W -0Wm");
    try testParse("-0w -0w -0wm", &.{ .implicit_return, .month_list_literal }, "-0W -0W -0Wm");
}

test "invalid month inputs" {
    const _std = @import("std");
    const _clock: _std.Io.Clock = .real;
    const _start = try _clock.now(_std.testing.io);
    const _file: _std.fs.File = .adaptFromNewApi(try _std.Io.Dir.cwd().createFile(_std.testing.io, @src().fn_name ++ ".log", .{}));
    defer _file.close();
    var _file_writer = _file.writer(&.{});
    const _writer = &_file_writer.interface;
    try _writer.writeAll(@src().fn_name);
    try _writer.flush();
    defer {
        _writer.print(": {d}ms\n", .{_start.durationTo(_clock.now(_std.testing.io) catch unreachable).toMilliseconds()}) catch unreachable;
        _writer.flush() catch unreachable;
    }
    try testNumberParserError("0m", error.InvalidCharacter);
    try testNumberParserError("1m", error.InvalidCharacter);
    try testNumberParserError("9m", error.InvalidCharacter);

    try testNumberParserError("00m", error.InvalidCharacter);
    try testNumberParserError("11m", error.InvalidCharacter);
    try testNumberParserError("99m", error.InvalidCharacter);

    try testNumberParserError("000m", error.InvalidCharacter);
    try testNumberParserError("111m", error.InvalidCharacter);
    try testNumberParserError("999m", error.InvalidCharacter);

    try testNumberParserError("0000m", error.Overflow);
    try testNumberParserError("0013m", error.Overflow);
    try testNumberParserError("9999m", error.Overflow);

    try testNumberParserError("00000m", error.InvalidCharacter);
    try testNumberParserError("11111m", error.InvalidCharacter);
    try testNumberParserError("99999m", error.InvalidCharacter);

    try testNumberParserError("000000m", error.Overflow);
    try testNumberParserError("000113m", error.Overflow);
    try testNumberParserError("999999m", error.Overflow);

    try testNumberParserError("1111111m", error.InvalidCharacter);

    try testNumberParserError("-1111111m", error.InvalidCharacter);

    try testNumberParserError("2000.1m", error.InvalidCharacter);
    try testNumberParserError("2000.00m", error.Overflow);
    try testNumberParserError("2000.13m", error.Overflow);

    try testParseError("1 2000.02m", &.{.parse_error});
    try testParseError("1 2 2000.03m", &.{.parse_error});

    try testParseError("1. 2000.02m", &.{.parse_error});
    try testParseError("1. 2. 2000.03m", &.{.parse_error});
}

test {
    @import("std").testing.refAllDecls(@This());
}
