const number_parser = @import("../number_parser.zig");
const Parse = @import("../../Parse.zig");
const testNumberParser = number_parser.testNumberParser;
const testNumberParserError = number_parser.testNumberParserError;
const testParse = Parse.testParse;
const testParseError = Parse.testParseError;
const null_real = number_parser.null_real;
const inf_real = number_parser.inf_real;

test "valid real inputs" {
    try testNumberParser("0e", .real, @as(f32, 0));
    try testNumberParser("1e", .real, @as(f32, 1));
    try testNumberParser("-1e", .real, @as(f32, -1));
    try testNumberParser(".1e", .real, @as(f32, 0.1));
    try testNumberParser("1.e", .real, @as(f32, 1));
    try testNumberParser("1.1e", .real, @as(f32, 1.1));
    try testNumberParser("-.1e", .real, @as(f32, -0.1));
    try testNumberParser("-1.e", .real, @as(f32, -1));
    try testNumberParser("-1.1e", .real, @as(f32, -1.1));
    try testNumberParser("0Ne", .real, @as(f32, null_real));
    try testNumberParser("0ne", .real, @as(f32, null_real));
    try testNumberParser("0We", .real, @as(f32, inf_real));
    try testNumberParser("0we", .real, @as(f32, inf_real));
    try testNumberParser("-0We", .real, @as(f32, -inf_real));
    try testNumberParser("-0we", .real, @as(f32, -inf_real));

    try testParse("1e", &.{ .implicit_return, .real_literal }, "1e");
    try testParse("1.e", &.{ .implicit_return, .real_literal }, "1e");
    try testParse("1.1e", &.{ .implicit_return, .real_literal }, "1.1e");
    try testParse("1 2e", &.{ .implicit_return, .real_list_literal }, "1 2e");
    try testParse("1 2.e", &.{ .implicit_return, .real_list_literal }, "1 2e");
    try testParse("1 2.2e", &.{ .implicit_return, .real_list_literal }, "1 2.2e");
    try testParse("1. 2e", &.{ .implicit_return, .real_list_literal }, "1 2e");
    try testParse("1. 2.e", &.{ .implicit_return, .real_list_literal }, "1 2e");
    try testParse("1. 2.2e", &.{ .implicit_return, .real_list_literal }, "1 2.2e");
    try testParse("1.1 2e", &.{ .implicit_return, .real_list_literal }, "1.1 2e");
    try testParse("1.1 2.e", &.{ .implicit_return, .real_list_literal }, "1.1 2e");
    try testParse("1.1 2.2e", &.{ .implicit_return, .real_list_literal }, "1.1 2.2e");
    try testParse("1 2 3e", &.{ .implicit_return, .real_list_literal }, "1 2 3e");
    try testParse("1 2 3.e", &.{ .implicit_return, .real_list_literal }, "1 2 3e");
    try testParse("1 2 3.3e", &.{ .implicit_return, .real_list_literal }, "1 2 3.3e");
    try testParse("1 2. 3e", &.{ .implicit_return, .real_list_literal }, "1 2 3e");
    try testParse("1 2. 3.e", &.{ .implicit_return, .real_list_literal }, "1 2 3e");
    try testParse("1 2. 3.3e", &.{ .implicit_return, .real_list_literal }, "1 2 3.3e");
    try testParse("1 2.2 3e", &.{ .implicit_return, .real_list_literal }, "1 2.2 3e");
    try testParse("1 2.2 3.e", &.{ .implicit_return, .real_list_literal }, "1 2.2 3e");
    try testParse("1 2.2 3.3e", &.{ .implicit_return, .real_list_literal }, "1 2.2 3.3e");
    try testParse("1. 2 3e", &.{ .implicit_return, .real_list_literal }, "1 2 3e");
    try testParse("1. 2 3.e", &.{ .implicit_return, .real_list_literal }, "1 2 3e");
    try testParse("1. 2 3.3e", &.{ .implicit_return, .real_list_literal }, "1 2 3.3e");
    try testParse("1. 2. 3e", &.{ .implicit_return, .real_list_literal }, "1 2 3e");
    try testParse("1. 2. 3.e", &.{ .implicit_return, .real_list_literal }, "1 2 3e");
    try testParse("1. 2. 3.3e", &.{ .implicit_return, .real_list_literal }, "1 2 3.3e");
    try testParse("1. 2.2 3e", &.{ .implicit_return, .real_list_literal }, "1 2.2 3e");
    try testParse("1. 2.2 3.e", &.{ .implicit_return, .real_list_literal }, "1 2.2 3e");
    try testParse("1. 2.2 3.3e", &.{ .implicit_return, .real_list_literal }, "1 2.2 3.3e");
    try testParse("1.1 2 3e", &.{ .implicit_return, .real_list_literal }, "1.1 2 3e");
    try testParse("1.1 2 3.e", &.{ .implicit_return, .real_list_literal }, "1.1 2 3e");
    try testParse("1.1 2 3.3e", &.{ .implicit_return, .real_list_literal }, "1.1 2 3.3e");
    try testParse("1.1 2. 3e", &.{ .implicit_return, .real_list_literal }, "1.1 2 3e");
    try testParse("1.1 2. 3.e", &.{ .implicit_return, .real_list_literal }, "1.1 2 3e");
    try testParse("1.1 2. 3.3e", &.{ .implicit_return, .real_list_literal }, "1.1 2 3.3e");
    try testParse("1.1 2.2 3e", &.{ .implicit_return, .real_list_literal }, "1.1 2.2 3e");
    try testParse("1.1 2.2 3.e", &.{ .implicit_return, .real_list_literal }, "1.1 2.2 3e");
    try testParse("1.1 2.2 3.3e", &.{ .implicit_return, .real_list_literal }, "1.1 2.2 3.3e");

    try testParse("0Ne", &.{ .implicit_return, .real_literal }, "0Ne");
    try testParse("0ne", &.{ .implicit_return, .real_literal }, "0Ne");
    try testParse("0We", &.{ .implicit_return, .real_literal }, "0We");
    try testParse("0we", &.{ .implicit_return, .real_literal }, "0We");
    try testParse("-0We", &.{ .implicit_return, .real_literal }, "-0We");
    try testParse("-0we", &.{ .implicit_return, .real_literal }, "-0We");

    try testParse("0N 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0Ne");
    try testParse("0N 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0Ne");
    try testParse("0N 0We", &.{ .implicit_return, .real_list_literal }, "0N 0We");
    try testParse("0N 0we", &.{ .implicit_return, .real_list_literal }, "0N 0We");
    try testParse("0N -0We", &.{ .implicit_return, .real_list_literal }, "0N -0We");
    try testParse("0N -0we", &.{ .implicit_return, .real_list_literal }, "0N -0We");
    try testParse("0n 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0Ne");
    try testParse("0n 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0Ne");
    try testParse("0n 0We", &.{ .implicit_return, .real_list_literal }, "0N 0We");
    try testParse("0n 0we", &.{ .implicit_return, .real_list_literal }, "0N 0We");
    try testParse("0n -0We", &.{ .implicit_return, .real_list_literal }, "0N -0We");
    try testParse("0n -0we", &.{ .implicit_return, .real_list_literal }, "0N -0We");
    try testParse("0W 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0Ne");
    try testParse("0W 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0Ne");
    try testParse("0W 0We", &.{ .implicit_return, .real_list_literal }, "0W 0We");
    try testParse("0W 0we", &.{ .implicit_return, .real_list_literal }, "0W 0We");
    try testParse("0W -0We", &.{ .implicit_return, .real_list_literal }, "0W -0We");
    try testParse("0W -0we", &.{ .implicit_return, .real_list_literal }, "0W -0We");
    try testParse("0w 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0Ne");
    try testParse("0w 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0Ne");
    try testParse("0w 0We", &.{ .implicit_return, .real_list_literal }, "0W 0We");
    try testParse("0w 0we", &.{ .implicit_return, .real_list_literal }, "0W 0We");
    try testParse("0w -0We", &.{ .implicit_return, .real_list_literal }, "0W -0We");
    try testParse("0w -0we", &.{ .implicit_return, .real_list_literal }, "0W -0We");
    try testParse("-0W 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0Ne");
    try testParse("-0W 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0Ne");
    try testParse("-0W 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0We");
    try testParse("-0W 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0We");
    try testParse("-0W -0We", &.{ .implicit_return, .real_list_literal }, "-0W -0We");
    try testParse("-0W -0we", &.{ .implicit_return, .real_list_literal }, "-0W -0We");
    try testParse("-0w 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0Ne");
    try testParse("-0w 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0Ne");
    try testParse("-0w 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0We");
    try testParse("-0w 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0We");
    try testParse("-0w -0We", &.{ .implicit_return, .real_list_literal }, "-0W -0We");
    try testParse("-0w -0we", &.{ .implicit_return, .real_list_literal }, "-0W -0We");

    try testParse("0N 0N 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0N 0Ne");
    try testParse("0N 0N 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0N 0Ne");
    try testParse("0N 0N 0We", &.{ .implicit_return, .real_list_literal }, "0N 0N 0We");
    try testParse("0N 0N 0we", &.{ .implicit_return, .real_list_literal }, "0N 0N 0We");
    try testParse("0N 0N -0We", &.{ .implicit_return, .real_list_literal }, "0N 0N -0We");
    try testParse("0N 0N -0we", &.{ .implicit_return, .real_list_literal }, "0N 0N -0We");
    try testParse("0N 0n 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0N 0Ne");
    try testParse("0N 0n 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0N 0Ne");
    try testParse("0N 0n 0We", &.{ .implicit_return, .real_list_literal }, "0N 0N 0We");
    try testParse("0N 0n 0we", &.{ .implicit_return, .real_list_literal }, "0N 0N 0We");
    try testParse("0N 0n -0We", &.{ .implicit_return, .real_list_literal }, "0N 0N -0We");
    try testParse("0N 0n -0we", &.{ .implicit_return, .real_list_literal }, "0N 0N -0We");
    try testParse("0N 0W 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0W 0Ne");
    try testParse("0N 0W 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0W 0Ne");
    try testParse("0N 0W 0We", &.{ .implicit_return, .real_list_literal }, "0N 0W 0We");
    try testParse("0N 0W 0we", &.{ .implicit_return, .real_list_literal }, "0N 0W 0We");
    try testParse("0N 0W -0We", &.{ .implicit_return, .real_list_literal }, "0N 0W -0We");
    try testParse("0N 0W -0we", &.{ .implicit_return, .real_list_literal }, "0N 0W -0We");
    try testParse("0N 0w 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0W 0Ne");
    try testParse("0N 0w 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0W 0Ne");
    try testParse("0N 0w 0We", &.{ .implicit_return, .real_list_literal }, "0N 0W 0We");
    try testParse("0N 0w 0we", &.{ .implicit_return, .real_list_literal }, "0N 0W 0We");
    try testParse("0N 0w -0We", &.{ .implicit_return, .real_list_literal }, "0N 0W -0We");
    try testParse("0N 0w -0we", &.{ .implicit_return, .real_list_literal }, "0N 0W -0We");
    try testParse("0N -0W 0Ne", &.{ .implicit_return, .real_list_literal }, "0N -0W 0Ne");
    try testParse("0N -0W 0ne", &.{ .implicit_return, .real_list_literal }, "0N -0W 0Ne");
    try testParse("0N -0W 0We", &.{ .implicit_return, .real_list_literal }, "0N -0W 0We");
    try testParse("0N -0W 0we", &.{ .implicit_return, .real_list_literal }, "0N -0W 0We");
    try testParse("0N -0W -0We", &.{ .implicit_return, .real_list_literal }, "0N -0W -0We");
    try testParse("0N -0W -0we", &.{ .implicit_return, .real_list_literal }, "0N -0W -0We");
    try testParse("0N -0w 0Ne", &.{ .implicit_return, .real_list_literal }, "0N -0W 0Ne");
    try testParse("0N -0w 0ne", &.{ .implicit_return, .real_list_literal }, "0N -0W 0Ne");
    try testParse("0N -0w 0We", &.{ .implicit_return, .real_list_literal }, "0N -0W 0We");
    try testParse("0N -0w 0we", &.{ .implicit_return, .real_list_literal }, "0N -0W 0We");
    try testParse("0N -0w -0We", &.{ .implicit_return, .real_list_literal }, "0N -0W -0We");
    try testParse("0N -0w -0we", &.{ .implicit_return, .real_list_literal }, "0N -0W -0We");
    try testParse("0n 0N 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0N 0Ne");
    try testParse("0n 0N 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0N 0Ne");
    try testParse("0n 0N 0We", &.{ .implicit_return, .real_list_literal }, "0N 0N 0We");
    try testParse("0n 0N 0we", &.{ .implicit_return, .real_list_literal }, "0N 0N 0We");
    try testParse("0n 0N -0We", &.{ .implicit_return, .real_list_literal }, "0N 0N -0We");
    try testParse("0n 0N -0we", &.{ .implicit_return, .real_list_literal }, "0N 0N -0We");
    try testParse("0n 0n 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0N 0Ne");
    try testParse("0n 0n 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0N 0Ne");
    try testParse("0n 0n 0We", &.{ .implicit_return, .real_list_literal }, "0N 0N 0We");
    try testParse("0n 0n 0we", &.{ .implicit_return, .real_list_literal }, "0N 0N 0We");
    try testParse("0n 0n -0We", &.{ .implicit_return, .real_list_literal }, "0N 0N -0We");
    try testParse("0n 0n -0we", &.{ .implicit_return, .real_list_literal }, "0N 0N -0We");
    try testParse("0n 0W 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0W 0Ne");
    try testParse("0n 0W 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0W 0Ne");
    try testParse("0n 0W 0We", &.{ .implicit_return, .real_list_literal }, "0N 0W 0We");
    try testParse("0n 0W 0we", &.{ .implicit_return, .real_list_literal }, "0N 0W 0We");
    try testParse("0n 0W -0We", &.{ .implicit_return, .real_list_literal }, "0N 0W -0We");
    try testParse("0n 0W -0we", &.{ .implicit_return, .real_list_literal }, "0N 0W -0We");
    try testParse("0n 0w 0Ne", &.{ .implicit_return, .real_list_literal }, "0N 0W 0Ne");
    try testParse("0n 0w 0ne", &.{ .implicit_return, .real_list_literal }, "0N 0W 0Ne");
    try testParse("0n 0w 0We", &.{ .implicit_return, .real_list_literal }, "0N 0W 0We");
    try testParse("0n 0w 0we", &.{ .implicit_return, .real_list_literal }, "0N 0W 0We");
    try testParse("0n 0w -0We", &.{ .implicit_return, .real_list_literal }, "0N 0W -0We");
    try testParse("0n 0w -0we", &.{ .implicit_return, .real_list_literal }, "0N 0W -0We");
    try testParse("0n -0W 0Ne", &.{ .implicit_return, .real_list_literal }, "0N -0W 0Ne");
    try testParse("0n -0W 0ne", &.{ .implicit_return, .real_list_literal }, "0N -0W 0Ne");
    try testParse("0n -0W 0We", &.{ .implicit_return, .real_list_literal }, "0N -0W 0We");
    try testParse("0n -0W 0we", &.{ .implicit_return, .real_list_literal }, "0N -0W 0We");
    try testParse("0n -0W -0We", &.{ .implicit_return, .real_list_literal }, "0N -0W -0We");
    try testParse("0n -0W -0we", &.{ .implicit_return, .real_list_literal }, "0N -0W -0We");
    try testParse("0n -0w 0Ne", &.{ .implicit_return, .real_list_literal }, "0N -0W 0Ne");
    try testParse("0n -0w 0ne", &.{ .implicit_return, .real_list_literal }, "0N -0W 0Ne");
    try testParse("0n -0w 0We", &.{ .implicit_return, .real_list_literal }, "0N -0W 0We");
    try testParse("0n -0w 0we", &.{ .implicit_return, .real_list_literal }, "0N -0W 0We");
    try testParse("0n -0w -0We", &.{ .implicit_return, .real_list_literal }, "0N -0W -0We");
    try testParse("0n -0w -0we", &.{ .implicit_return, .real_list_literal }, "0N -0W -0We");
    try testParse("0W 0N 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0N 0Ne");
    try testParse("0W 0N 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0N 0Ne");
    try testParse("0W 0N 0We", &.{ .implicit_return, .real_list_literal }, "0W 0N 0We");
    try testParse("0W 0N 0we", &.{ .implicit_return, .real_list_literal }, "0W 0N 0We");
    try testParse("0W 0N -0We", &.{ .implicit_return, .real_list_literal }, "0W 0N -0We");
    try testParse("0W 0N -0we", &.{ .implicit_return, .real_list_literal }, "0W 0N -0We");
    try testParse("0W 0n 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0N 0Ne");
    try testParse("0W 0n 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0N 0Ne");
    try testParse("0W 0n 0We", &.{ .implicit_return, .real_list_literal }, "0W 0N 0We");
    try testParse("0W 0n 0we", &.{ .implicit_return, .real_list_literal }, "0W 0N 0We");
    try testParse("0W 0n -0We", &.{ .implicit_return, .real_list_literal }, "0W 0N -0We");
    try testParse("0W 0n -0we", &.{ .implicit_return, .real_list_literal }, "0W 0N -0We");
    try testParse("0W 0W 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0W 0Ne");
    try testParse("0W 0W 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0W 0Ne");
    try testParse("0W 0W 0We", &.{ .implicit_return, .real_list_literal }, "0W 0W 0We");
    try testParse("0W 0W 0we", &.{ .implicit_return, .real_list_literal }, "0W 0W 0We");
    try testParse("0W 0W -0We", &.{ .implicit_return, .real_list_literal }, "0W 0W -0We");
    try testParse("0W 0W -0we", &.{ .implicit_return, .real_list_literal }, "0W 0W -0We");
    try testParse("0W 0w 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0W 0Ne");
    try testParse("0W 0w 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0W 0Ne");
    try testParse("0W 0w 0We", &.{ .implicit_return, .real_list_literal }, "0W 0W 0We");
    try testParse("0W 0w 0we", &.{ .implicit_return, .real_list_literal }, "0W 0W 0We");
    try testParse("0W 0w -0We", &.{ .implicit_return, .real_list_literal }, "0W 0W -0We");
    try testParse("0W 0w -0we", &.{ .implicit_return, .real_list_literal }, "0W 0W -0We");
    try testParse("0W -0W 0Ne", &.{ .implicit_return, .real_list_literal }, "0W -0W 0Ne");
    try testParse("0W -0W 0ne", &.{ .implicit_return, .real_list_literal }, "0W -0W 0Ne");
    try testParse("0W -0W 0We", &.{ .implicit_return, .real_list_literal }, "0W -0W 0We");
    try testParse("0W -0W 0we", &.{ .implicit_return, .real_list_literal }, "0W -0W 0We");
    try testParse("0W -0W -0We", &.{ .implicit_return, .real_list_literal }, "0W -0W -0We");
    try testParse("0W -0W -0we", &.{ .implicit_return, .real_list_literal }, "0W -0W -0We");
    try testParse("0W -0w 0Ne", &.{ .implicit_return, .real_list_literal }, "0W -0W 0Ne");
    try testParse("0W -0w 0ne", &.{ .implicit_return, .real_list_literal }, "0W -0W 0Ne");
    try testParse("0W -0w 0We", &.{ .implicit_return, .real_list_literal }, "0W -0W 0We");
    try testParse("0W -0w 0we", &.{ .implicit_return, .real_list_literal }, "0W -0W 0We");
    try testParse("0W -0w -0We", &.{ .implicit_return, .real_list_literal }, "0W -0W -0We");
    try testParse("0W -0w -0we", &.{ .implicit_return, .real_list_literal }, "0W -0W -0We");
    try testParse("0w 0N 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0N 0Ne");
    try testParse("0w 0N 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0N 0Ne");
    try testParse("0w 0N 0We", &.{ .implicit_return, .real_list_literal }, "0W 0N 0We");
    try testParse("0w 0N 0we", &.{ .implicit_return, .real_list_literal }, "0W 0N 0We");
    try testParse("0w 0N -0We", &.{ .implicit_return, .real_list_literal }, "0W 0N -0We");
    try testParse("0w 0N -0we", &.{ .implicit_return, .real_list_literal }, "0W 0N -0We");
    try testParse("0w 0n 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0N 0Ne");
    try testParse("0w 0n 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0N 0Ne");
    try testParse("0w 0n 0We", &.{ .implicit_return, .real_list_literal }, "0W 0N 0We");
    try testParse("0w 0n 0we", &.{ .implicit_return, .real_list_literal }, "0W 0N 0We");
    try testParse("0w 0n -0We", &.{ .implicit_return, .real_list_literal }, "0W 0N -0We");
    try testParse("0w 0n -0we", &.{ .implicit_return, .real_list_literal }, "0W 0N -0We");
    try testParse("0w 0W 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0W 0Ne");
    try testParse("0w 0W 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0W 0Ne");
    try testParse("0w 0W 0We", &.{ .implicit_return, .real_list_literal }, "0W 0W 0We");
    try testParse("0w 0W 0we", &.{ .implicit_return, .real_list_literal }, "0W 0W 0We");
    try testParse("0w 0W -0We", &.{ .implicit_return, .real_list_literal }, "0W 0W -0We");
    try testParse("0w 0W -0we", &.{ .implicit_return, .real_list_literal }, "0W 0W -0We");
    try testParse("0w 0w 0Ne", &.{ .implicit_return, .real_list_literal }, "0W 0W 0Ne");
    try testParse("0w 0w 0ne", &.{ .implicit_return, .real_list_literal }, "0W 0W 0Ne");
    try testParse("0w 0w 0We", &.{ .implicit_return, .real_list_literal }, "0W 0W 0We");
    try testParse("0w 0w 0we", &.{ .implicit_return, .real_list_literal }, "0W 0W 0We");
    try testParse("0w 0w -0We", &.{ .implicit_return, .real_list_literal }, "0W 0W -0We");
    try testParse("0w 0w -0we", &.{ .implicit_return, .real_list_literal }, "0W 0W -0We");
    try testParse("0w -0W 0Ne", &.{ .implicit_return, .real_list_literal }, "0W -0W 0Ne");
    try testParse("0w -0W 0ne", &.{ .implicit_return, .real_list_literal }, "0W -0W 0Ne");
    try testParse("0w -0W 0We", &.{ .implicit_return, .real_list_literal }, "0W -0W 0We");
    try testParse("0w -0W 0we", &.{ .implicit_return, .real_list_literal }, "0W -0W 0We");
    try testParse("0w -0W -0We", &.{ .implicit_return, .real_list_literal }, "0W -0W -0We");
    try testParse("0w -0W -0we", &.{ .implicit_return, .real_list_literal }, "0W -0W -0We");
    try testParse("0w -0w 0Ne", &.{ .implicit_return, .real_list_literal }, "0W -0W 0Ne");
    try testParse("0w -0w 0ne", &.{ .implicit_return, .real_list_literal }, "0W -0W 0Ne");
    try testParse("0w -0w 0We", &.{ .implicit_return, .real_list_literal }, "0W -0W 0We");
    try testParse("0w -0w 0we", &.{ .implicit_return, .real_list_literal }, "0W -0W 0We");
    try testParse("0w -0w -0We", &.{ .implicit_return, .real_list_literal }, "0W -0W -0We");
    try testParse("0w -0w -0we", &.{ .implicit_return, .real_list_literal }, "0W -0W -0We");
    try testParse("-0W 0N 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0Ne");
    try testParse("-0W 0N 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0Ne");
    try testParse("-0W 0N 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0We");
    try testParse("-0W 0N 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0We");
    try testParse("-0W 0N -0We", &.{ .implicit_return, .real_list_literal }, "-0W 0N -0We");
    try testParse("-0W 0N -0we", &.{ .implicit_return, .real_list_literal }, "-0W 0N -0We");
    try testParse("-0W 0n 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0Ne");
    try testParse("-0W 0n 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0Ne");
    try testParse("-0W 0n 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0We");
    try testParse("-0W 0n 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0We");
    try testParse("-0W 0n -0We", &.{ .implicit_return, .real_list_literal }, "-0W 0N -0We");
    try testParse("-0W 0n -0we", &.{ .implicit_return, .real_list_literal }, "-0W 0N -0We");
    try testParse("-0W 0W 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0Ne");
    try testParse("-0W 0W 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0Ne");
    try testParse("-0W 0W 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0We");
    try testParse("-0W 0W 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0We");
    try testParse("-0W 0W -0We", &.{ .implicit_return, .real_list_literal }, "-0W 0W -0We");
    try testParse("-0W 0W -0we", &.{ .implicit_return, .real_list_literal }, "-0W 0W -0We");
    try testParse("-0W 0w 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0Ne");
    try testParse("-0W 0w 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0Ne");
    try testParse("-0W 0w 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0We");
    try testParse("-0W 0w 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0We");
    try testParse("-0W 0w -0We", &.{ .implicit_return, .real_list_literal }, "-0W 0W -0We");
    try testParse("-0W 0w -0we", &.{ .implicit_return, .real_list_literal }, "-0W 0W -0We");
    try testParse("-0W -0W 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0Ne");
    try testParse("-0W -0W 0ne", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0Ne");
    try testParse("-0W -0W 0We", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0We");
    try testParse("-0W -0W 0we", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0We");
    try testParse("-0W -0W -0We", &.{ .implicit_return, .real_list_literal }, "-0W -0W -0We");
    try testParse("-0W -0W -0we", &.{ .implicit_return, .real_list_literal }, "-0W -0W -0We");
    try testParse("-0W -0w 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0Ne");
    try testParse("-0W -0w 0ne", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0Ne");
    try testParse("-0W -0w 0We", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0We");
    try testParse("-0W -0w 0we", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0We");
    try testParse("-0W -0w -0We", &.{ .implicit_return, .real_list_literal }, "-0W -0W -0We");
    try testParse("-0W -0w -0we", &.{ .implicit_return, .real_list_literal }, "-0W -0W -0We");
    try testParse("-0w 0N 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0Ne");
    try testParse("-0w 0N 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0Ne");
    try testParse("-0w 0N 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0We");
    try testParse("-0w 0N 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0We");
    try testParse("-0w 0N -0We", &.{ .implicit_return, .real_list_literal }, "-0W 0N -0We");
    try testParse("-0w 0N -0we", &.{ .implicit_return, .real_list_literal }, "-0W 0N -0We");
    try testParse("-0w 0n 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0Ne");
    try testParse("-0w 0n 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0Ne");
    try testParse("-0w 0n 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0We");
    try testParse("-0w 0n 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0N 0We");
    try testParse("-0w 0n -0We", &.{ .implicit_return, .real_list_literal }, "-0W 0N -0We");
    try testParse("-0w 0n -0we", &.{ .implicit_return, .real_list_literal }, "-0W 0N -0We");
    try testParse("-0w 0W 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0Ne");
    try testParse("-0w 0W 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0Ne");
    try testParse("-0w 0W 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0We");
    try testParse("-0w 0W 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0We");
    try testParse("-0w 0W -0We", &.{ .implicit_return, .real_list_literal }, "-0W 0W -0We");
    try testParse("-0w 0W -0we", &.{ .implicit_return, .real_list_literal }, "-0W 0W -0We");
    try testParse("-0w 0w 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0Ne");
    try testParse("-0w 0w 0ne", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0Ne");
    try testParse("-0w 0w 0We", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0We");
    try testParse("-0w 0w 0we", &.{ .implicit_return, .real_list_literal }, "-0W 0W 0We");
    try testParse("-0w 0w -0We", &.{ .implicit_return, .real_list_literal }, "-0W 0W -0We");
    try testParse("-0w 0w -0we", &.{ .implicit_return, .real_list_literal }, "-0W 0W -0We");
    try testParse("-0w -0W 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0Ne");
    try testParse("-0w -0W 0ne", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0Ne");
    try testParse("-0w -0W 0We", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0We");
    try testParse("-0w -0W 0we", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0We");
    try testParse("-0w -0W -0We", &.{ .implicit_return, .real_list_literal }, "-0W -0W -0We");
    try testParse("-0w -0W -0we", &.{ .implicit_return, .real_list_literal }, "-0W -0W -0We");
    try testParse("-0w -0w 0Ne", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0Ne");
    try testParse("-0w -0w 0ne", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0Ne");
    try testParse("-0w -0w 0We", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0We");
    try testParse("-0w -0w 0we", &.{ .implicit_return, .real_list_literal }, "-0W -0W 0We");
    try testParse("-0w -0w -0We", &.{ .implicit_return, .real_list_literal }, "-0W -0W -0We");
    try testParse("-0w -0w -0we", &.{ .implicit_return, .real_list_literal }, "-0W -0W -0We");
}

test "invalid real inputs" {
    try testNumberParserError("0ee", error.InvalidCharacter);
    try testNumberParserError("1ee", error.InvalidCharacter);
    try testNumberParserError("-1ee", error.InvalidCharacter);
    try testNumberParserError(".1ee", error.InvalidCharacter);
    try testNumberParserError("1.ee", error.InvalidCharacter);
    try testNumberParserError("1.1ee", error.InvalidCharacter);
    try testNumberParserError("-.1ee", error.InvalidCharacter);
    try testNumberParserError("-1.ee", error.InvalidCharacter);
    try testNumberParserError("-1.1ee", error.InvalidCharacter);
}

test "real scientific notation" {
    return error.SkipZigTest;
}
