const number_parser = @import("../number_parser.zig");
const Parse = @import("../../Parse.zig");
const testNumberParser = number_parser.testNumberParser;
const testNumberParserError = number_parser.testNumberParserError;
const testParse = Parse.testParse;
const testParseError = Parse.testParseError;
const null_int = number_parser.null_int;
const inf_int = number_parser.inf_int;

test "valid second inputs" {
    try testNumberParser("0nv", .second, null_int);
    try testNumberParser("0Nv", .second, null_int);
    try testNumberParser("0wv", .second, inf_int);
    try testNumberParser("0Wv", .second, inf_int);
    try testNumberParser("-0wv", .second, -inf_int);
    try testNumberParser("-0Wv", .second, -inf_int);

    try testNumberParser("0v", .second, 0);
    try testNumberParser("9v", .second, 32400);
    try testNumberParser("-9v", .second, -32400);

    try testNumberParser("00v", .second, 0);
    try testNumberParser("99v", .second, 356400);
    try testNumberParser("-99v", .second, -356400);

    try testNumberParser("000v", .second, 0);
    try testNumberParser("959v", .second, 35940);
    try testNumberParser("-959v", .second, -35940);

    try testNumberParser("0000v", .second, 0);
    try testNumberParser("9959v", .second, 359940);
    try testNumberParser("-9959v", .second, -359940);

    try testNumberParser("00000v", .second, 0);
    try testNumberParser("99959v", .second, 3599940);
    try testNumberParser("-99959v", .second, -3599940);

    try testNumberParser("000000v", .second, 0);
    try testNumberParser("995959v", .second, 359999);
    try testNumberParser("-995959v", .second, -359999);

    try testNumberParser("0000000v", .second, 0);
    try testNumberParser("9995959v", .second, 3599999);
    try testNumberParser("-9995959v", .second, -3599999);

    try testNumberParser("00000000v", .second, 0);
    try testNumberParser("99995959v", .second, 35999999);
    try testNumberParser("-99995959v", .second, -35999999);

    try testNumberParser("000000000v", .second, 0);
    try testNumberParser("999995959v", .second, 359999999);
    try testNumberParser("-999995959v", .second, -359999999);

    try testNumberParser("0000000000v", .second, 0);
    try testNumberParser("9999995959v", .second, -694967297);
    try testNumberParser("-9999995959v", .second, 694967297);

    try testNumberParser("00000000000v", .second, 0);
    try testNumberParser("99999995959v", .second, 1640261631);
    try testNumberParser("-99999995959v", .second, -1640261631);

    try testNumberParser("000000000000v", .second, 0);
    try testNumberParser("999999995959v", .second, -777252865);
    try testNumberParser("-999999995959v", .second, 777252865);

    try testNumberParser("0000000000000v", .second, 0);
    try testNumberParser("9999999995959v", .second, 817405951);
    try testNumberParser("-9999999995959v", .second, -817405951);

    try testNumberParser("00000000000000v", .second, 0);
    try testNumberParser("21474836475959v", .second, -1);
    try testNumberParser("-21474836475959v", .second, 1);

    try testNumberParser("00:00:00", .second, 0);
    try testNumberParser("99:59:59", .second, 359999);
    try testNumberParser("-99:59:59", .second, -359999);

    try testNumberParser("000:00:00", .second, 0);
    try testNumberParser("999:59:59", .second, 3599999);

    try testParse("0 9 -9v", &.{ .implicit_return, .second_list_literal }, "00:00:00 09:00:00 -09:00:00");
    try testParse("00 99 -99v", &.{ .implicit_return, .second_list_literal }, "00:00:00 99:00:00 -99:00:00");
    try testParse("000 959 -959v", &.{ .implicit_return, .second_list_literal }, "00:00:00 09:59:00 -09:59:00");
    try testParse("0000 9959 -9959v", &.{ .implicit_return, .second_list_literal }, "00:00:00 99:59:00 -99:59:00");
    try testParse("00000 99959 -99959v", &.{ .implicit_return, .second_list_literal }, "00:00:00 **:59:00 -**:59:00");
    try testParse("00000000000000 21474836475959 -21474836475959v", &.{ .implicit_return, .second_list_literal }, "00:00:00 -00:00:01 00:00:01");
    try testParse("00:00:00 99:59:59 -99:59:59 000:00:00 999:59:59", &.{ .implicit_return, .second_list_literal }, "00:00:00 99:59:59 -99:59:59 00:00:00 **:59:59");

    try testParse("0Nv", &.{ .implicit_return, .second_literal }, "0Nv");
    try testParse("0nv", &.{ .implicit_return, .second_literal }, "0Nv");
    try testParse("0Wv", &.{ .implicit_return, .second_literal }, "0Wv");
    try testParse("0wv", &.{ .implicit_return, .second_literal }, "0Wv");
    try testParse("-0Wv", &.{ .implicit_return, .second_literal }, "-0Wv");
    try testParse("-0wv", &.{ .implicit_return, .second_literal }, "-0Wv");

    try testParse("0N 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0Nv");
    try testParse("0N 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0Nv");
    try testParse("0N 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0Wv");
    try testParse("0N 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0Wv");
    try testParse("0N -0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0Wv");
    try testParse("0N -0wv", &.{ .implicit_return, .second_list_literal }, "0N -0Wv");
    try testParse("0n 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0Nv");
    try testParse("0n 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0Nv");
    try testParse("0n 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0Wv");
    try testParse("0n 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0Wv");
    try testParse("0n -0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0Wv");
    try testParse("0n -0wv", &.{ .implicit_return, .second_list_literal }, "0N -0Wv");
    try testParse("0W 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0Nv");
    try testParse("0W 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0Nv");
    try testParse("0W 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0Wv");
    try testParse("0W 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0Wv");
    try testParse("0W -0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0Wv");
    try testParse("0W -0wv", &.{ .implicit_return, .second_list_literal }, "0W -0Wv");
    try testParse("0w 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0Nv");
    try testParse("0w 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0Nv");
    try testParse("0w 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0Wv");
    try testParse("0w 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0Wv");
    try testParse("0w -0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0Wv");
    try testParse("0w -0wv", &.{ .implicit_return, .second_list_literal }, "0W -0Wv");
    try testParse("-0W 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0Nv");
    try testParse("-0W 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0Nv");
    try testParse("-0W 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0Wv");
    try testParse("-0W 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0Wv");
    try testParse("-0W -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0Wv");
    try testParse("-0W -0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0Wv");
    try testParse("-0w 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0Nv");
    try testParse("-0w 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0Nv");
    try testParse("-0w 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0Wv");
    try testParse("-0w 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0Wv");
    try testParse("-0w -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0Wv");
    try testParse("-0w -0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0Wv");

    try testParse("0N 0N 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Nv");
    try testParse("0N 0N 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Nv");
    try testParse("0N 0N 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Wv");
    try testParse("0N 0N 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Wv");
    try testParse("0N 0N -0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0N -0Wv");
    try testParse("0N 0N -0wv", &.{ .implicit_return, .second_list_literal }, "0N 0N -0Wv");
    try testParse("0N 0n 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Nv");
    try testParse("0N 0n 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Nv");
    try testParse("0N 0n 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Wv");
    try testParse("0N 0n 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Wv");
    try testParse("0N 0n -0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0N -0Wv");
    try testParse("0N 0n -0wv", &.{ .implicit_return, .second_list_literal }, "0N 0N -0Wv");
    try testParse("0N 0W 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Nv");
    try testParse("0N 0W 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Nv");
    try testParse("0N 0W 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Wv");
    try testParse("0N 0W 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Wv");
    try testParse("0N 0W -0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0W -0Wv");
    try testParse("0N 0W -0wv", &.{ .implicit_return, .second_list_literal }, "0N 0W -0Wv");
    try testParse("0N 0w 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Nv");
    try testParse("0N 0w 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Nv");
    try testParse("0N 0w 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Wv");
    try testParse("0N 0w 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Wv");
    try testParse("0N 0w -0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0W -0Wv");
    try testParse("0N 0w -0wv", &.{ .implicit_return, .second_list_literal }, "0N 0W -0Wv");
    try testParse("0N -0W 0Nv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Nv");
    try testParse("0N -0W 0nv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Nv");
    try testParse("0N -0W 0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Wv");
    try testParse("0N -0W 0wv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Wv");
    try testParse("0N -0W -0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0W -0Wv");
    try testParse("0N -0W -0wv", &.{ .implicit_return, .second_list_literal }, "0N -0W -0Wv");
    try testParse("0N -0w 0Nv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Nv");
    try testParse("0N -0w 0nv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Nv");
    try testParse("0N -0w 0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Wv");
    try testParse("0N -0w 0wv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Wv");
    try testParse("0N -0w -0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0W -0Wv");
    try testParse("0N -0w -0wv", &.{ .implicit_return, .second_list_literal }, "0N -0W -0Wv");
    try testParse("0n 0N 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Nv");
    try testParse("0n 0N 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Nv");
    try testParse("0n 0N 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Wv");
    try testParse("0n 0N 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Wv");
    try testParse("0n 0N -0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0N -0Wv");
    try testParse("0n 0N -0wv", &.{ .implicit_return, .second_list_literal }, "0N 0N -0Wv");
    try testParse("0n 0n 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Nv");
    try testParse("0n 0n 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Nv");
    try testParse("0n 0n 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Wv");
    try testParse("0n 0n 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0N 0Wv");
    try testParse("0n 0n -0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0N -0Wv");
    try testParse("0n 0n -0wv", &.{ .implicit_return, .second_list_literal }, "0N 0N -0Wv");
    try testParse("0n 0W 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Nv");
    try testParse("0n 0W 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Nv");
    try testParse("0n 0W 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Wv");
    try testParse("0n 0W 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Wv");
    try testParse("0n 0W -0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0W -0Wv");
    try testParse("0n 0W -0wv", &.{ .implicit_return, .second_list_literal }, "0N 0W -0Wv");
    try testParse("0n 0w 0Nv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Nv");
    try testParse("0n 0w 0nv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Nv");
    try testParse("0n 0w 0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Wv");
    try testParse("0n 0w 0wv", &.{ .implicit_return, .second_list_literal }, "0N 0W 0Wv");
    try testParse("0n 0w -0Wv", &.{ .implicit_return, .second_list_literal }, "0N 0W -0Wv");
    try testParse("0n 0w -0wv", &.{ .implicit_return, .second_list_literal }, "0N 0W -0Wv");
    try testParse("0n -0W 0Nv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Nv");
    try testParse("0n -0W 0nv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Nv");
    try testParse("0n -0W 0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Wv");
    try testParse("0n -0W 0wv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Wv");
    try testParse("0n -0W -0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0W -0Wv");
    try testParse("0n -0W -0wv", &.{ .implicit_return, .second_list_literal }, "0N -0W -0Wv");
    try testParse("0n -0w 0Nv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Nv");
    try testParse("0n -0w 0nv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Nv");
    try testParse("0n -0w 0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Wv");
    try testParse("0n -0w 0wv", &.{ .implicit_return, .second_list_literal }, "0N -0W 0Wv");
    try testParse("0n -0w -0Wv", &.{ .implicit_return, .second_list_literal }, "0N -0W -0Wv");
    try testParse("0n -0w -0wv", &.{ .implicit_return, .second_list_literal }, "0N -0W -0Wv");
    try testParse("0W 0N 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Nv");
    try testParse("0W 0N 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Nv");
    try testParse("0W 0N 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Wv");
    try testParse("0W 0N 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Wv");
    try testParse("0W 0N -0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0N -0Wv");
    try testParse("0W 0N -0wv", &.{ .implicit_return, .second_list_literal }, "0W 0N -0Wv");
    try testParse("0W 0n 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Nv");
    try testParse("0W 0n 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Nv");
    try testParse("0W 0n 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Wv");
    try testParse("0W 0n 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Wv");
    try testParse("0W 0n -0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0N -0Wv");
    try testParse("0W 0n -0wv", &.{ .implicit_return, .second_list_literal }, "0W 0N -0Wv");
    try testParse("0W 0W 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Nv");
    try testParse("0W 0W 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Nv");
    try testParse("0W 0W 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Wv");
    try testParse("0W 0W 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Wv");
    try testParse("0W 0W -0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0W -0Wv");
    try testParse("0W 0W -0wv", &.{ .implicit_return, .second_list_literal }, "0W 0W -0Wv");
    try testParse("0W 0w 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Nv");
    try testParse("0W 0w 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Nv");
    try testParse("0W 0w 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Wv");
    try testParse("0W 0w 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Wv");
    try testParse("0W 0w -0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0W -0Wv");
    try testParse("0W 0w -0wv", &.{ .implicit_return, .second_list_literal }, "0W 0W -0Wv");
    try testParse("0W -0W 0Nv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Nv");
    try testParse("0W -0W 0nv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Nv");
    try testParse("0W -0W 0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Wv");
    try testParse("0W -0W 0wv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Wv");
    try testParse("0W -0W -0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0W -0Wv");
    try testParse("0W -0W -0wv", &.{ .implicit_return, .second_list_literal }, "0W -0W -0Wv");
    try testParse("0W -0w 0Nv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Nv");
    try testParse("0W -0w 0nv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Nv");
    try testParse("0W -0w 0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Wv");
    try testParse("0W -0w 0wv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Wv");
    try testParse("0W -0w -0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0W -0Wv");
    try testParse("0W -0w -0wv", &.{ .implicit_return, .second_list_literal }, "0W -0W -0Wv");
    try testParse("0w 0N 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Nv");
    try testParse("0w 0N 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Nv");
    try testParse("0w 0N 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Wv");
    try testParse("0w 0N 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Wv");
    try testParse("0w 0N -0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0N -0Wv");
    try testParse("0w 0N -0wv", &.{ .implicit_return, .second_list_literal }, "0W 0N -0Wv");
    try testParse("0w 0n 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Nv");
    try testParse("0w 0n 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Nv");
    try testParse("0w 0n 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Wv");
    try testParse("0w 0n 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0N 0Wv");
    try testParse("0w 0n -0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0N -0Wv");
    try testParse("0w 0n -0wv", &.{ .implicit_return, .second_list_literal }, "0W 0N -0Wv");
    try testParse("0w 0W 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Nv");
    try testParse("0w 0W 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Nv");
    try testParse("0w 0W 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Wv");
    try testParse("0w 0W 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Wv");
    try testParse("0w 0W -0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0W -0Wv");
    try testParse("0w 0W -0wv", &.{ .implicit_return, .second_list_literal }, "0W 0W -0Wv");
    try testParse("0w 0w 0Nv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Nv");
    try testParse("0w 0w 0nv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Nv");
    try testParse("0w 0w 0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Wv");
    try testParse("0w 0w 0wv", &.{ .implicit_return, .second_list_literal }, "0W 0W 0Wv");
    try testParse("0w 0w -0Wv", &.{ .implicit_return, .second_list_literal }, "0W 0W -0Wv");
    try testParse("0w 0w -0wv", &.{ .implicit_return, .second_list_literal }, "0W 0W -0Wv");
    try testParse("0w -0W 0Nv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Nv");
    try testParse("0w -0W 0nv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Nv");
    try testParse("0w -0W 0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Wv");
    try testParse("0w -0W 0wv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Wv");
    try testParse("0w -0W -0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0W -0Wv");
    try testParse("0w -0W -0wv", &.{ .implicit_return, .second_list_literal }, "0W -0W -0Wv");
    try testParse("0w -0w 0Nv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Nv");
    try testParse("0w -0w 0nv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Nv");
    try testParse("0w -0w 0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Wv");
    try testParse("0w -0w 0wv", &.{ .implicit_return, .second_list_literal }, "0W -0W 0Wv");
    try testParse("0w -0w -0Wv", &.{ .implicit_return, .second_list_literal }, "0W -0W -0Wv");
    try testParse("0w -0w -0wv", &.{ .implicit_return, .second_list_literal }, "0W -0W -0Wv");
    try testParse("-0W 0N 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Nv");
    try testParse("-0W 0N 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Nv");
    try testParse("-0W 0N 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Wv");
    try testParse("-0W 0N 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Wv");
    try testParse("-0W 0N -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N -0Wv");
    try testParse("-0W 0N -0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N -0Wv");
    try testParse("-0W 0n 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Nv");
    try testParse("-0W 0n 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Nv");
    try testParse("-0W 0n 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Wv");
    try testParse("-0W 0n 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Wv");
    try testParse("-0W 0n -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N -0Wv");
    try testParse("-0W 0n -0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N -0Wv");
    try testParse("-0W 0W 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Nv");
    try testParse("-0W 0W 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Nv");
    try testParse("-0W 0W 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Wv");
    try testParse("-0W 0W 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Wv");
    try testParse("-0W 0W -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W -0Wv");
    try testParse("-0W 0W -0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W -0Wv");
    try testParse("-0W 0w 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Nv");
    try testParse("-0W 0w 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Nv");
    try testParse("-0W 0w 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Wv");
    try testParse("-0W 0w 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Wv");
    try testParse("-0W 0w -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W -0Wv");
    try testParse("-0W 0w -0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W -0Wv");
    try testParse("-0W -0W 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Nv");
    try testParse("-0W -0W 0nv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Nv");
    try testParse("-0W -0W 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Wv");
    try testParse("-0W -0W 0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Wv");
    try testParse("-0W -0W -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W -0Wv");
    try testParse("-0W -0W -0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W -0Wv");
    try testParse("-0W -0w 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Nv");
    try testParse("-0W -0w 0nv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Nv");
    try testParse("-0W -0w 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Wv");
    try testParse("-0W -0w 0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Wv");
    try testParse("-0W -0w -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W -0Wv");
    try testParse("-0W -0w -0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W -0Wv");
    try testParse("-0w 0N 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Nv");
    try testParse("-0w 0N 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Nv");
    try testParse("-0w 0N 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Wv");
    try testParse("-0w 0N 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Wv");
    try testParse("-0w 0N -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N -0Wv");
    try testParse("-0w 0N -0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N -0Wv");
    try testParse("-0w 0n 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Nv");
    try testParse("-0w 0n 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Nv");
    try testParse("-0w 0n 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Wv");
    try testParse("-0w 0n 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N 0Wv");
    try testParse("-0w 0n -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N -0Wv");
    try testParse("-0w 0n -0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0N -0Wv");
    try testParse("-0w 0W 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Nv");
    try testParse("-0w 0W 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Nv");
    try testParse("-0w 0W 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Wv");
    try testParse("-0w 0W 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Wv");
    try testParse("-0w 0W -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W -0Wv");
    try testParse("-0w 0W -0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W -0Wv");
    try testParse("-0w 0w 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Nv");
    try testParse("-0w 0w 0nv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Nv");
    try testParse("-0w 0w 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Wv");
    try testParse("-0w 0w 0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W 0Wv");
    try testParse("-0w 0w -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W -0Wv");
    try testParse("-0w 0w -0wv", &.{ .implicit_return, .second_list_literal }, "-0W 0W -0Wv");
    try testParse("-0w -0W 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Nv");
    try testParse("-0w -0W 0nv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Nv");
    try testParse("-0w -0W 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Wv");
    try testParse("-0w -0W 0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Wv");
    try testParse("-0w -0W -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W -0Wv");
    try testParse("-0w -0W -0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W -0Wv");
    try testParse("-0w -0w 0Nv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Nv");
    try testParse("-0w -0w 0nv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Nv");
    try testParse("-0w -0w 0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Wv");
    try testParse("-0w -0w 0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W 0Wv");
    try testParse("-0w -0w -0Wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W -0Wv");
    try testParse("-0w -0w -0wv", &.{ .implicit_return, .second_list_literal }, "-0W -0W -0Wv");
}

test "invalid second inputs" {
    try testNumberParserError("00:0:0", error.InvalidCharacter);
    try testNumberParserError("00:0:00", error.InvalidCharacter);
    try testNumberParserError("00:00:0", error.InvalidCharacter);

    try testNumberParserError("00:60:00", error.Overflow);
    try testNumberParserError("00:00:60", error.Overflow);
    try testNumberParserError("99:60:59", error.Overflow);
    try testNumberParserError("99:59:60", error.Overflow);
    try testNumberParserError("-99:60:59", error.Overflow);
    try testNumberParserError("-99:59:60", error.Overflow);

    try testNumberParserError("000:60:00", error.Overflow);
    try testNumberParserError("000:00:60", error.Overflow);
    try testNumberParserError("999:60:59", error.Overflow);
    try testNumberParserError("999:59:60", error.Overflow);
    try testNumberParserError("999:60:59", error.Overflow);
    try testNumberParserError("999:59:60", error.Overflow);
    try testNumberParserError("-999:59:59", error.InvalidCharacter);

    try testNumberParserError("060v", error.Overflow);
    try testNumberParserError("960v", error.Overflow);
    try testNumberParserError("-960v", error.Overflow);

    try testNumberParserError("0060v", error.Overflow);
    try testNumberParserError("9960v", error.Overflow);
    try testNumberParserError("-9960v", error.Overflow);

    try testNumberParserError("00060v", error.Overflow);
    try testNumberParserError("99960v", error.Overflow);
    try testNumberParserError("-99960v", error.Overflow);

    try testNumberParserError("006000v", error.Overflow);
    try testNumberParserError("000060v", error.Overflow);
    try testNumberParserError("996059v", error.Overflow);
    try testNumberParserError("995960v", error.Overflow);
    try testNumberParserError("-996059v", error.Overflow);
    try testNumberParserError("-995960v", error.Overflow);

    try testNumberParserError("000000006000v", error.Overflow);
    try testNumberParserError("000000000060v", error.Overflow);
    try testNumberParserError("21474836485959v", error.Overflow);
    try testNumberParserError("21474836476059v", error.Overflow);
    try testNumberParserError("21474836475960v", error.Overflow);
    try testNumberParserError("-21474836485959v", error.Overflow);
    try testNumberParserError("-21474836476059v", error.Overflow);
    try testNumberParserError("-21474836475960v", error.Overflow);
}
