const number_parser = @import("../number_parser.zig");
const Parse = @import("../../Parse.zig");
const testNumberParser = number_parser.testNumberParser;
const testNumberParserError = number_parser.testNumberParserError;
const testParse = Parse.testParse;
const testParseError = Parse.testParseError;
const null_short = number_parser.null_short;
const inf_short = number_parser.inf_short;

test "valid short inputs" {
    try testNumberParser("0h", .short, 0);
    try testNumberParser("1h", .short, 1);
    try testNumberParser("-1h", .short, -1);
    try testNumberParser("32766h", .short, 32766);
    try testNumberParser("-32766h", .short, -32766);
    try testNumberParser("0Nh", .short, null_short);
    try testNumberParser("0nh", .short, null_short);
    try testNumberParser("0Wh", .short, inf_short);
    try testNumberParser("0wh", .short, inf_short);
    try testNumberParser("32767h", .short, inf_short);
    try testNumberParser("-0Wh", .short, -inf_short);
    try testNumberParser("-0wh", .short, -inf_short);
    try testNumberParser("-32767h", .short, -inf_short);

    try testParse("1 2h", &.{ .implicit_return, .short_list_literal }, "1 2h");
    try testParse("1 2 3h", &.{ .implicit_return, .short_list_literal }, "1 2 3h");

    try testParse("0N 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0Nh");
    try testParse("0N 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0Nh");
    try testParse("0N 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0Wh");
    try testParse("0N 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0Wh");
    try testParse("0N -0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0Wh");
    try testParse("0N -0wh", &.{ .implicit_return, .short_list_literal }, "0N -0Wh");
    try testParse("0n 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0Nh");
    try testParse("0n 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0Nh");
    try testParse("0n 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0Wh");
    try testParse("0n 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0Wh");
    try testParse("0n -0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0Wh");
    try testParse("0n -0wh", &.{ .implicit_return, .short_list_literal }, "0N -0Wh");
    try testParse("0W 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0Nh");
    try testParse("0W 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0Nh");
    try testParse("0W 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0Wh");
    try testParse("0W 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0Wh");
    try testParse("0W -0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0Wh");
    try testParse("0W -0wh", &.{ .implicit_return, .short_list_literal }, "0W -0Wh");
    try testParse("0w 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0Nh");
    try testParse("0w 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0Nh");
    try testParse("0w 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0Wh");
    try testParse("0w 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0Wh");
    try testParse("0w -0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0Wh");
    try testParse("0w -0wh", &.{ .implicit_return, .short_list_literal }, "0W -0Wh");
    try testParse("-0W 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0Nh");
    try testParse("-0W 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0Nh");
    try testParse("-0W 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0Wh");
    try testParse("-0W 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0Wh");
    try testParse("-0W -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0Wh");
    try testParse("-0W -0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0Wh");
    try testParse("-0w 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0Nh");
    try testParse("-0w 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0Nh");
    try testParse("-0w 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0Wh");
    try testParse("-0w 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0Wh");
    try testParse("-0w -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0Wh");
    try testParse("-0w -0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0Wh");

    try testParse("0N 0N 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Nh");
    try testParse("0N 0N 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Nh");
    try testParse("0N 0N 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Wh");
    try testParse("0N 0N 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Wh");
    try testParse("0N 0N -0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0N -0Wh");
    try testParse("0N 0N -0wh", &.{ .implicit_return, .short_list_literal }, "0N 0N -0Wh");
    try testParse("0N 0n 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Nh");
    try testParse("0N 0n 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Nh");
    try testParse("0N 0n 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Wh");
    try testParse("0N 0n 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Wh");
    try testParse("0N 0n -0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0N -0Wh");
    try testParse("0N 0n -0wh", &.{ .implicit_return, .short_list_literal }, "0N 0N -0Wh");
    try testParse("0N 0W 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Nh");
    try testParse("0N 0W 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Nh");
    try testParse("0N 0W 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Wh");
    try testParse("0N 0W 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Wh");
    try testParse("0N 0W -0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0W -0Wh");
    try testParse("0N 0W -0wh", &.{ .implicit_return, .short_list_literal }, "0N 0W -0Wh");
    try testParse("0N 0w 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Nh");
    try testParse("0N 0w 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Nh");
    try testParse("0N 0w 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Wh");
    try testParse("0N 0w 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Wh");
    try testParse("0N 0w -0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0W -0Wh");
    try testParse("0N 0w -0wh", &.{ .implicit_return, .short_list_literal }, "0N 0W -0Wh");
    try testParse("0N -0W 0Nh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Nh");
    try testParse("0N -0W 0nh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Nh");
    try testParse("0N -0W 0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Wh");
    try testParse("0N -0W 0wh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Wh");
    try testParse("0N -0W -0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0W -0Wh");
    try testParse("0N -0W -0wh", &.{ .implicit_return, .short_list_literal }, "0N -0W -0Wh");
    try testParse("0N -0w 0Nh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Nh");
    try testParse("0N -0w 0nh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Nh");
    try testParse("0N -0w 0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Wh");
    try testParse("0N -0w 0wh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Wh");
    try testParse("0N -0w -0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0W -0Wh");
    try testParse("0N -0w -0wh", &.{ .implicit_return, .short_list_literal }, "0N -0W -0Wh");
    try testParse("0n 0N 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Nh");
    try testParse("0n 0N 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Nh");
    try testParse("0n 0N 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Wh");
    try testParse("0n 0N 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Wh");
    try testParse("0n 0N -0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0N -0Wh");
    try testParse("0n 0N -0wh", &.{ .implicit_return, .short_list_literal }, "0N 0N -0Wh");
    try testParse("0n 0n 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Nh");
    try testParse("0n 0n 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Nh");
    try testParse("0n 0n 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Wh");
    try testParse("0n 0n 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0N 0Wh");
    try testParse("0n 0n -0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0N -0Wh");
    try testParse("0n 0n -0wh", &.{ .implicit_return, .short_list_literal }, "0N 0N -0Wh");
    try testParse("0n 0W 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Nh");
    try testParse("0n 0W 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Nh");
    try testParse("0n 0W 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Wh");
    try testParse("0n 0W 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Wh");
    try testParse("0n 0W -0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0W -0Wh");
    try testParse("0n 0W -0wh", &.{ .implicit_return, .short_list_literal }, "0N 0W -0Wh");
    try testParse("0n 0w 0Nh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Nh");
    try testParse("0n 0w 0nh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Nh");
    try testParse("0n 0w 0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Wh");
    try testParse("0n 0w 0wh", &.{ .implicit_return, .short_list_literal }, "0N 0W 0Wh");
    try testParse("0n 0w -0Wh", &.{ .implicit_return, .short_list_literal }, "0N 0W -0Wh");
    try testParse("0n 0w -0wh", &.{ .implicit_return, .short_list_literal }, "0N 0W -0Wh");
    try testParse("0n -0W 0Nh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Nh");
    try testParse("0n -0W 0nh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Nh");
    try testParse("0n -0W 0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Wh");
    try testParse("0n -0W 0wh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Wh");
    try testParse("0n -0W -0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0W -0Wh");
    try testParse("0n -0W -0wh", &.{ .implicit_return, .short_list_literal }, "0N -0W -0Wh");
    try testParse("0n -0w 0Nh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Nh");
    try testParse("0n -0w 0nh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Nh");
    try testParse("0n -0w 0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Wh");
    try testParse("0n -0w 0wh", &.{ .implicit_return, .short_list_literal }, "0N -0W 0Wh");
    try testParse("0n -0w -0Wh", &.{ .implicit_return, .short_list_literal }, "0N -0W -0Wh");
    try testParse("0n -0w -0wh", &.{ .implicit_return, .short_list_literal }, "0N -0W -0Wh");
    try testParse("0W 0N 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Nh");
    try testParse("0W 0N 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Nh");
    try testParse("0W 0N 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Wh");
    try testParse("0W 0N 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Wh");
    try testParse("0W 0N -0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0N -0Wh");
    try testParse("0W 0N -0wh", &.{ .implicit_return, .short_list_literal }, "0W 0N -0Wh");
    try testParse("0W 0n 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Nh");
    try testParse("0W 0n 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Nh");
    try testParse("0W 0n 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Wh");
    try testParse("0W 0n 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Wh");
    try testParse("0W 0n -0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0N -0Wh");
    try testParse("0W 0n -0wh", &.{ .implicit_return, .short_list_literal }, "0W 0N -0Wh");
    try testParse("0W 0W 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Nh");
    try testParse("0W 0W 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Nh");
    try testParse("0W 0W 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Wh");
    try testParse("0W 0W 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Wh");
    try testParse("0W 0W -0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0W -0Wh");
    try testParse("0W 0W -0wh", &.{ .implicit_return, .short_list_literal }, "0W 0W -0Wh");
    try testParse("0W 0w 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Nh");
    try testParse("0W 0w 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Nh");
    try testParse("0W 0w 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Wh");
    try testParse("0W 0w 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Wh");
    try testParse("0W 0w -0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0W -0Wh");
    try testParse("0W 0w -0wh", &.{ .implicit_return, .short_list_literal }, "0W 0W -0Wh");
    try testParse("0W -0W 0Nh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Nh");
    try testParse("0W -0W 0nh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Nh");
    try testParse("0W -0W 0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Wh");
    try testParse("0W -0W 0wh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Wh");
    try testParse("0W -0W -0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0W -0Wh");
    try testParse("0W -0W -0wh", &.{ .implicit_return, .short_list_literal }, "0W -0W -0Wh");
    try testParse("0W -0w 0Nh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Nh");
    try testParse("0W -0w 0nh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Nh");
    try testParse("0W -0w 0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Wh");
    try testParse("0W -0w 0wh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Wh");
    try testParse("0W -0w -0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0W -0Wh");
    try testParse("0W -0w -0wh", &.{ .implicit_return, .short_list_literal }, "0W -0W -0Wh");
    try testParse("0w 0N 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Nh");
    try testParse("0w 0N 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Nh");
    try testParse("0w 0N 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Wh");
    try testParse("0w 0N 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Wh");
    try testParse("0w 0N -0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0N -0Wh");
    try testParse("0w 0N -0wh", &.{ .implicit_return, .short_list_literal }, "0W 0N -0Wh");
    try testParse("0w 0n 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Nh");
    try testParse("0w 0n 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Nh");
    try testParse("0w 0n 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Wh");
    try testParse("0w 0n 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0N 0Wh");
    try testParse("0w 0n -0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0N -0Wh");
    try testParse("0w 0n -0wh", &.{ .implicit_return, .short_list_literal }, "0W 0N -0Wh");
    try testParse("0w 0W 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Nh");
    try testParse("0w 0W 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Nh");
    try testParse("0w 0W 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Wh");
    try testParse("0w 0W 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Wh");
    try testParse("0w 0W -0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0W -0Wh");
    try testParse("0w 0W -0wh", &.{ .implicit_return, .short_list_literal }, "0W 0W -0Wh");
    try testParse("0w 0w 0Nh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Nh");
    try testParse("0w 0w 0nh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Nh");
    try testParse("0w 0w 0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Wh");
    try testParse("0w 0w 0wh", &.{ .implicit_return, .short_list_literal }, "0W 0W 0Wh");
    try testParse("0w 0w -0Wh", &.{ .implicit_return, .short_list_literal }, "0W 0W -0Wh");
    try testParse("0w 0w -0wh", &.{ .implicit_return, .short_list_literal }, "0W 0W -0Wh");
    try testParse("0w -0W 0Nh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Nh");
    try testParse("0w -0W 0nh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Nh");
    try testParse("0w -0W 0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Wh");
    try testParse("0w -0W 0wh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Wh");
    try testParse("0w -0W -0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0W -0Wh");
    try testParse("0w -0W -0wh", &.{ .implicit_return, .short_list_literal }, "0W -0W -0Wh");
    try testParse("0w -0w 0Nh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Nh");
    try testParse("0w -0w 0nh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Nh");
    try testParse("0w -0w 0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Wh");
    try testParse("0w -0w 0wh", &.{ .implicit_return, .short_list_literal }, "0W -0W 0Wh");
    try testParse("0w -0w -0Wh", &.{ .implicit_return, .short_list_literal }, "0W -0W -0Wh");
    try testParse("0w -0w -0wh", &.{ .implicit_return, .short_list_literal }, "0W -0W -0Wh");
    try testParse("-0W 0N 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Nh");
    try testParse("-0W 0N 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Nh");
    try testParse("-0W 0N 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Wh");
    try testParse("-0W 0N 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Wh");
    try testParse("-0W 0N -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N -0Wh");
    try testParse("-0W 0N -0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N -0Wh");
    try testParse("-0W 0n 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Nh");
    try testParse("-0W 0n 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Nh");
    try testParse("-0W 0n 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Wh");
    try testParse("-0W 0n 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Wh");
    try testParse("-0W 0n -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N -0Wh");
    try testParse("-0W 0n -0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N -0Wh");
    try testParse("-0W 0W 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Nh");
    try testParse("-0W 0W 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Nh");
    try testParse("-0W 0W 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Wh");
    try testParse("-0W 0W 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Wh");
    try testParse("-0W 0W -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W -0Wh");
    try testParse("-0W 0W -0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W -0Wh");
    try testParse("-0W 0w 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Nh");
    try testParse("-0W 0w 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Nh");
    try testParse("-0W 0w 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Wh");
    try testParse("-0W 0w 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Wh");
    try testParse("-0W 0w -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W -0Wh");
    try testParse("-0W 0w -0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W -0Wh");
    try testParse("-0W -0W 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Nh");
    try testParse("-0W -0W 0nh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Nh");
    try testParse("-0W -0W 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Wh");
    try testParse("-0W -0W 0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Wh");
    try testParse("-0W -0W -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W -0Wh");
    try testParse("-0W -0W -0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W -0Wh");
    try testParse("-0W -0w 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Nh");
    try testParse("-0W -0w 0nh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Nh");
    try testParse("-0W -0w 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Wh");
    try testParse("-0W -0w 0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Wh");
    try testParse("-0W -0w -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W -0Wh");
    try testParse("-0W -0w -0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W -0Wh");
    try testParse("-0w 0N 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Nh");
    try testParse("-0w 0N 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Nh");
    try testParse("-0w 0N 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Wh");
    try testParse("-0w 0N 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Wh");
    try testParse("-0w 0N -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N -0Wh");
    try testParse("-0w 0N -0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N -0Wh");
    try testParse("-0w 0n 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Nh");
    try testParse("-0w 0n 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Nh");
    try testParse("-0w 0n 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Wh");
    try testParse("-0w 0n 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N 0Wh");
    try testParse("-0w 0n -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N -0Wh");
    try testParse("-0w 0n -0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0N -0Wh");
    try testParse("-0w 0W 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Nh");
    try testParse("-0w 0W 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Nh");
    try testParse("-0w 0W 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Wh");
    try testParse("-0w 0W 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Wh");
    try testParse("-0w 0W -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W -0Wh");
    try testParse("-0w 0W -0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W -0Wh");
    try testParse("-0w 0w 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Nh");
    try testParse("-0w 0w 0nh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Nh");
    try testParse("-0w 0w 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Wh");
    try testParse("-0w 0w 0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W 0Wh");
    try testParse("-0w 0w -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W -0Wh");
    try testParse("-0w 0w -0wh", &.{ .implicit_return, .short_list_literal }, "-0W 0W -0Wh");
    try testParse("-0w -0W 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Nh");
    try testParse("-0w -0W 0nh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Nh");
    try testParse("-0w -0W 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Wh");
    try testParse("-0w -0W 0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Wh");
    try testParse("-0w -0W -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W -0Wh");
    try testParse("-0w -0W -0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W -0Wh");
    try testParse("-0w -0w 0Nh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Nh");
    try testParse("-0w -0w 0nh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Nh");
    try testParse("-0w -0w 0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Wh");
    try testParse("-0w -0w 0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W 0Wh");
    try testParse("-0w -0w -0Wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W -0Wh");
    try testParse("-0w -0w -0wh", &.{ .implicit_return, .short_list_literal }, "-0W -0W -0Wh");
}

test "invalid short inputs" {
    try testNumberParserError("0hh", error.InvalidCharacter);
    try testNumberParserError("1hh", error.InvalidCharacter);
    try testNumberParserError("-1hh", error.InvalidCharacter);
    try testNumberParserError("32766hh", error.InvalidCharacter);
    try testNumberParserError("-32766hh", error.InvalidCharacter);
    try testNumberParserError(".1h", error.InvalidCharacter);
    try testNumberParserError("1.h", error.InvalidCharacter);
    try testNumberParserError("1.1h", error.InvalidCharacter);
    try testNumberParserError("32768h", error.Overflow);
    try testNumberParserError("-32768h", error.Overflow);
    try testNumberParserError("-32769h", error.Overflow);

    try testParseError("1. 2h", &.{.parse_error});
    try testParseError("1. 2. 3h", &.{.parse_error});
}
