const std = @import("std");
const Io = std.Io;
const Allocator = std.mem.Allocator;

const Uri = @This();

percent_encoded: []const u8,

pub fn parse(gpa: Allocator, text: []const u8) !Uri {
    var uri: std.Uri = try .parse(text);

    var arena_instance: std.heap.ArenaAllocator = .init(gpa);
    defer arena_instance.deinit();

    if (std.ascii.eqlIgnoreCase(uri.scheme, "file")) {
        // Clients differ in which characters they percent-encode. Decode the
        // path and re-encode it so URIs from the client compare byte-equal
        // with URIs generated by `fromPath`. Caveat: an encoded `/` (`%2F`)
        // in a path segment becomes a literal separator, which cannot occur
        // in a valid file path anyway.
        // Note: the temporary is required; writing the result directly into
        // `uri.path` retags the union before the right-hand side reads it.
        const raw_path = try uri.path.toRawMaybeAlloc(arena_instance.allocator());
        uri.path = .{ .raw = raw_path };

        // `std.Uri` parses `file:///x` with a null host and would re-format
        // it as `file:/x`; force the empty authority so the canonical form
        // keeps the `file:///` shape clients expect.
        if (uri.host == null) uri.host = .{ .percent_encoded = "" };
    }

    var buffer: Io.Writer.Allocating = .init(gpa);
    defer buffer.deinit();

    try uri.format(&buffer.writer);

    return .{ .percent_encoded = try buffer.toOwnedSlice() };
}

/// `path` must be an absolute file system path.
pub fn fromPath(gpa: Allocator, path: []const u8) !Uri {
    std.debug.assert(std.fs.path.isAbsolute(path));

    // TODO: Windows drive letters and backslash separators.
    var buffer: Io.Writer.Allocating = .init(gpa);
    defer buffer.deinit();

    try buffer.writer.writeAll("file://");
    try (std.Uri.Component{ .raw = path }).formatPath(&buffer.writer);

    return .{ .percent_encoded = try buffer.toOwnedSlice() };
}

/// Converts a `file:` URI into a file system path.
pub fn toFsPath(uri: Uri, allocator: Allocator) ![]u8 {
    const parsed: std.Uri = std.Uri.parse(uri.percent_encoded) catch return error.InvalidUri;
    if (!std.ascii.eqlIgnoreCase(parsed.scheme, "file")) return error.UnsupportedScheme;

    var buffer: Io.Writer.Allocating = .init(allocator);
    defer buffer.deinit();

    try parsed.path.formatRaw(&buffer.writer);

    return buffer.toOwnedSlice();
}

pub fn deinit(uri: Uri, gpa: Allocator) void {
    gpa.free(uri.percent_encoded);
}

pub fn dupe(uri: Uri, gpa: Allocator) !Uri {
    return .{ .percent_encoded = try gpa.dupe(u8, uri.percent_encoded) };
}

pub fn eql(a: Uri, b: Uri) bool {
    return std.mem.eql(u8, a.percent_encoded, b.percent_encoded);
}

pub fn ArrayHashMap(comptime V: type) type {
    return std.ArrayHashMapUnmanaged(Uri, V, Context, true);
}

const Context = struct {
    pub fn hash(_: Context, key: Uri) u32 {
        return std.array_hash_map.hashString(key.percent_encoded);
    }

    pub fn eql(_: Context, a: Uri, b: Uri, _: usize) bool {
        return std.array_hash_map.eqlString(a.percent_encoded, b.percent_encoded);
    }
};

test "fromPath/toFsPath round-trip" {
    const gpa = std.testing.allocator;

    const uri = try fromPath(gpa, "/tmp/my dir/file.q");
    defer uri.deinit(gpa);
    try std.testing.expectEqualStrings("file:///tmp/my%20dir/file.q", uri.percent_encoded);

    const path = try uri.toFsPath(gpa);
    defer gpa.free(path);
    try std.testing.expectEqualStrings("/tmp/my dir/file.q", path);
}

test "parse canonicalizes percent-encoding" {
    const gpa = std.testing.allocator;

    const encoded = try parse(gpa, "file:///a%2Db.q");
    defer encoded.deinit(gpa);
    const plain = try parse(gpa, "file:///a-b.q");
    defer plain.deinit(gpa);
    const from_path = try fromPath(gpa, "/a-b.q");
    defer from_path.deinit(gpa);

    try std.testing.expect(encoded.eql(plain));
    try std.testing.expect(encoded.eql(from_path));

    const spaced = try parse(gpa, "file:///my%20dir/f.q");
    defer spaced.deinit(gpa);
    try std.testing.expectEqualStrings("file:///my%20dir/f.q", spaced.percent_encoded);
}

test "toFsPath rejects non-file schemes" {
    const gpa = std.testing.allocator;

    const uri = try parse(gpa, "untitled:Untitled-1");
    defer uri.deinit(gpa);
    try std.testing.expectError(error.UnsupportedScheme, uri.toFsPath(gpa));
}

test {
    std.testing.refAllDecls(@This());
}
